/* Generated by vigil transpile — do not edit. */
#include "vigil_generated.h"
#include <math.h>
#include <string.h>
#include "vigil/transpile_rt.h"
#include "vigil/value.h"

vigil_value_t *vigil_fn_constants[1];
size_t vigil_fn_constant_counts[1];

vigil_reg_t vigil_fn_0(vigil_tc_t *tc);

vigil_reg_t vigil_fn_0(vigil_tc_t *tc)
{
    vigil_reg_t r[21];
    memset(r, 0, sizeof(r));
    tc->constants = vigil_fn_constants[0];
    tc->constant_count = vigil_fn_constant_counts[0];

L_0:;
    r[0].i = (int64_t)0LL;
L_1:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "example", 7, &_s, NULL); vigil_value_init_object(&r[1].v, &_s); }
L_2:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "Demonstrates the args.Parser API", 32, &_s, NULL); vigil_value_init_object(&r[2].v, &_s); }
L_3:;
    vigil_tc_call_native(tc, (uint64_t *)r, 0, 3, 3, NULL);
L_5:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "verbose", 7, &_s, NULL); vigil_value_init_object(&r[1].v, &_s); }
L_6:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 126, 2, 0, 0, NULL);
L_7:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "v", 1, &_s, NULL); vigil_value_init_object(&r[2].v, &_s); }
L_8:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "Enable verbose output", 21, &_s, NULL); vigil_value_init_object(&r[3].v, &_s); }
L_9:;
    vigil_tc_call_native(tc, (uint64_t *)r, 0, 4, 7, NULL);
L_11:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "dry-run", 7, &_s, NULL); vigil_value_init_object(&r[1].v, &_s); }
L_12:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "n", 1, &_s, NULL); vigil_value_init_object(&r[2].v, &_s); }
L_13:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 126, 3, 0, 0, NULL);
L_14:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "Show what would be done", 23, &_s, NULL); vigil_value_init_object(&r[3].v, &_s); }
L_15:;
    vigil_tc_call_native(tc, (uint64_t *)r, 0, 4, 11, NULL);
L_17:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "input", 5, &_s, NULL); vigil_value_init_object(&r[1].v, &_s); }
L_18:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 126, 2, 0, 0, NULL);
L_19:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "i", 1, &_s, NULL); vigil_value_init_object(&r[2].v, &_s); }
L_20:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "Input file path", 15, &_s, NULL); vigil_value_init_object(&r[3].v, &_s); }
L_21:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "", 0, &_s, NULL); vigil_value_init_object(&r[4].v, &_s); }
L_22:;
    vigil_tc_call_native(tc, (uint64_t *)r, 0, 5, 16, NULL);
L_24:;
    vigil_tc_call_native(tc, (uint64_t *)r, 0, 1, 17, NULL);
L_26:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 126, 1, 0, 0, NULL);
L_27:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "output", 6, &_s, NULL); vigil_value_init_object(&r[1].v, &_s); }
L_28:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "o", 1, &_s, NULL); vigil_value_init_object(&r[2].v, &_s); }
L_29:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 126, 3, 0, 0, NULL);
L_30:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "Output file path", 16, &_s, NULL); vigil_value_init_object(&r[3].v, &_s); }
L_31:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 126, 4, 0, 0, NULL);
L_32:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "out.txt", 7, &_s, NULL); vigil_value_init_object(&r[4].v, &_s); }
L_33:;
    vigil_tc_call_native(tc, (uint64_t *)r, 0, 5, 22, NULL);
L_35:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "jobs", 4, &_s, NULL); vigil_value_init_object(&r[1].v, &_s); }
L_36:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 126, 2, 0, 0, NULL);
L_37:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "j", 1, &_s, NULL); vigil_value_init_object(&r[2].v, &_s); }
L_38:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "Number of parallel jobs", 23, &_s, NULL); vigil_value_init_object(&r[3].v, &_s); }
L_39:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "4", 1, &_s, NULL); vigil_value_init_object(&r[4].v, &_s); }
L_40:;
    vigil_tc_call_native(tc, (uint64_t *)r, 0, 5, 27, NULL);
L_42:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "filter", 6, &_s, NULL); vigil_value_init_object(&r[1].v, &_s); }
L_43:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "f", 1, &_s, NULL); vigil_value_init_object(&r[2].v, &_s); }
L_44:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 126, 3, 0, 0, NULL);
L_45:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "Filter pattern (repeatable)", 27, &_s, NULL); vigil_value_init_object(&r[3].v, &_s); }
L_46:;
    vigil_tc_call_native(tc, (uint64_t *)r, 0, 4, 31, NULL);
L_48:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "FILE", 4, &_s, NULL); vigil_value_init_object(&r[1].v, &_s); }
L_49:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 126, 2, 0, 0, NULL);
L_50:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "File to process", 15, &_s, NULL); vigil_value_init_object(&r[2].v, &_s); }
L_51:;
    vigil_tc_call_native(tc, (uint64_t *)r, 0, 3, 34, NULL);
L_53:;
    r[1].i = (int64_t)0LL;
L_54:;
    vigil_tc_move_reg(&r[2].v, r[1].v);
L_55:;
    vigil_tc_call_native(tc, (uint64_t *)r, 3, 0, 36, NULL);
L_57:;
    if ((int32_t)r[2].i < (int32_t)r[3].i) goto L_59;
L_58:;
    goto L_87;
L_59:;
    goto L_62;
L_60:;
    r[1].i = (int64_t)((int32_t)r[1].i + (int32_t)1);
L_61:;
    goto L_54;
L_62:;
    vigil_tc_move_reg(&r[2].v, r[1].v);
L_63:;
    vigil_tc_call_native(tc, (uint64_t *)r, 2, 1, 38, NULL);
L_65:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 126, 3, 0, 0, NULL);
L_66:;
    vigil_tc_move_reg(&r[3].v, r[2].v);
L_67:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 126, 4, 0, 0, NULL);
L_68:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "--help", 6, &_s, NULL); vigil_value_init_object(&r[4].v, &_s); }
L_69:;
    r[3].i = vigil_tc_values_equal((uint64_t *)r, 3, 4);
L_70:;
    if (vigil_tc_is_truthy(r[3].v)) goto L_72;
L_71:;
    goto L_73;
L_72:;
    goto L_76;
L_73:;
    vigil_tc_move_reg(&r[3].v, r[2].v);
L_74:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "-h", 2, &_s, NULL); vigil_value_init_object(&r[4].v, &_s); }
L_75:;
    r[3].i = vigil_tc_values_equal((uint64_t *)r, 3, 4);
L_76:;
    if (vigil_tc_is_truthy(r[3].v)) goto L_78;
L_77:;
    goto L_86;
L_78:;
    vigil_tc_move_reg(&r[3].v, r[0].v);
L_79:;
    vigil_tc_call_native(tc, (uint64_t *)r, 3, 1, 41, NULL);
L_81:;
    vigil_tc_call_native(tc, (uint64_t *)r, 3, 1, 42, NULL);
L_83:;
    r[3].i = (int64_t)0LL;
L_84:;
L_85:;
    tc->ret_count = 1;
    return r[3];
L_86:;
    goto L_60;
L_87:;
    vigil_tc_move_reg(&r[1].v, r[0].v);
L_88:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 126, 2, 0, 0, NULL);
L_89:;
    r[2].i = (int64_t)0LL;
L_90:;
    vigil_tc_call_native(tc, (uint64_t *)r, 1, 2, 45, NULL);
L_92:;
    vigil_tc_move_reg(&r[2].v, r[1].v);
L_93:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 126, 3, 0, 0, NULL);
L_94:;
    r[3].v = vigil_value_copy(&tc->constants[46]);
L_95:;
    r[2].i = vigil_tc_values_equal((uint64_t *)r, 2, 3);
L_96:;
    r[2].i = !r[2].i;
L_97:;
    if (vigil_tc_is_truthy(r[2].v)) goto L_99;
L_98:;
    goto L_110;
L_99:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "Error: parse failed", 19, &_s, NULL); vigil_value_init_object(&r[2].v, &_s); }
L_100:;
    vigil_tc_call_native(tc, (uint64_t *)r, 2, 1, 48, NULL);
L_102:;
    vigil_tc_move_reg(&r[2].v, r[0].v);
L_103:;
    vigil_tc_call_native(tc, (uint64_t *)r, 2, 1, 49, NULL);
L_105:;
    vigil_tc_call_native(tc, (uint64_t *)r, 2, 1, 50, NULL);
L_107:;
    r[2].i = (int64_t)1LL;
L_108:;
L_109:;
    tc->ret_count = 1;
    return r[2];
L_110:;
    vigil_tc_move_reg(&r[2].v, r[0].v);
L_111:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "verbose", 7, &_s, NULL); vigil_value_init_object(&r[3].v, &_s); }
L_112:;
    vigil_tc_call_native(tc, (uint64_t *)r, 2, 2, 53, NULL);
L_114:;
    vigil_tc_move_reg(&r[3].v, r[0].v);
L_115:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 126, 4, 0, 0, NULL);
L_116:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "dry-run", 7, &_s, NULL); vigil_value_init_object(&r[4].v, &_s); }
L_117:;
    vigil_tc_call_native(tc, (uint64_t *)r, 3, 2, 55, NULL);
L_119:;
    vigil_tc_move_reg(&r[4].v, r[0].v);
L_120:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "input", 5, &_s, NULL); vigil_value_init_object(&r[5].v, &_s); }
L_121:;
    vigil_tc_call_native(tc, (uint64_t *)r, 4, 2, 57, NULL);
L_123:;
    vigil_tc_move_reg(&r[5].v, r[0].v);
L_124:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "output", 6, &_s, NULL); vigil_value_init_object(&r[6].v, &_s); }
L_125:;
    vigil_tc_call_native(tc, (uint64_t *)r, 5, 2, 59, NULL);
L_127:;
    vigil_tc_move_reg(&r[6].v, r[0].v);
L_128:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "jobs", 4, &_s, NULL); vigil_value_init_object(&r[7].v, &_s); }
L_129:;
    vigil_tc_call_native(tc, (uint64_t *)r, 6, 2, 61, NULL);
L_131:;
    vigil_tc_move_reg(&r[7].v, r[0].v);
L_132:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "filter", 6, &_s, NULL); vigil_value_init_object(&r[8].v, &_s); }
L_133:;
    vigil_tc_call_native(tc, (uint64_t *)r, 7, 2, 63, NULL);
L_135:;
    vigil_tc_move_reg(&r[8].v, r[0].v);
L_136:;
    vigil_tc_call_native(tc, (uint64_t *)r, 8, 1, 64, NULL);
L_138:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "verbose:     ", 13, &_s, NULL); vigil_value_init_object(&r[9].v, &_s); }
L_139:;
    vigil_tc_move_reg(&r[10].v, r[2].v);
L_140:;
    vigil_tc_to_string(tc, &r[10].v, &r[10].v, NULL);
L_141:;
    vigil_tc_generic_add(tc, &r[9].v, &r[9].v, &r[10].v, NULL);
L_142:;
    vigil_tc_call_native(tc, (uint64_t *)r, 9, 1, 66, NULL);
L_144:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "dry-run:     ", 13, &_s, NULL); vigil_value_init_object(&r[9].v, &_s); }
L_145:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 126, 10, 0, 0, NULL);
L_146:;
    vigil_tc_move_reg(&r[10].v, r[3].v);
L_147:;
    vigil_tc_to_string(tc, &r[10].v, &r[10].v, NULL);
L_148:;
    vigil_tc_generic_add(tc, &r[9].v, &r[9].v, &r[10].v, NULL);
L_149:;
    vigil_tc_call_native(tc, (uint64_t *)r, 9, 1, 68, NULL);
L_151:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "input:       ", 13, &_s, NULL); vigil_value_init_object(&r[9].v, &_s); }
L_152:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 126, 10, 0, 0, NULL);
L_153:;
L_154:;
    vigil_tc_generic_add(tc, &r[9].v, &r[9].v, &r[4].v, NULL);
L_155:;
    vigil_tc_call_native(tc, (uint64_t *)r, 9, 1, 70, NULL);
L_157:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "output:      ", 13, &_s, NULL); vigil_value_init_object(&r[9].v, &_s); }
L_158:;
L_159:;
    vigil_tc_generic_add(tc, &r[9].v, &r[9].v, &r[5].v, NULL);
L_160:;
    vigil_tc_call_native(tc, (uint64_t *)r, 9, 1, 72, NULL);
L_162:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "jobs:        ", 13, &_s, NULL); vigil_value_init_object(&r[9].v, &_s); }
L_163:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 126, 10, 0, 0, NULL);
L_164:;
L_165:;
    vigil_tc_generic_add(tc, &r[9].v, &r[9].v, &r[6].v, NULL);
L_166:;
    vigil_tc_call_native(tc, (uint64_t *)r, 9, 1, 74, NULL);
L_168:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "filters:     ", 13, &_s, NULL); vigil_value_init_object(&r[9].v, &_s); }
L_169:;
    vigil_tc_move_reg(&r[10].v, r[7].v);
L_170:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 89, 10, 10, 0, NULL);
L_171:;
    vigil_tc_to_string(tc, &r[10].v, &r[10].v, NULL);
L_172:;
    vigil_tc_generic_add(tc, &r[9].v, &r[9].v, &r[10].v, NULL);
L_173:;
    vigil_tc_call_native(tc, (uint64_t *)r, 9, 1, 76, NULL);
L_175:;
    r[9].i = (int64_t)0LL;
L_176:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 126, 10, 0, 0, NULL);
L_177:;
    vigil_tc_move_reg(&r[10].v, r[9].v);
L_178:;
    vigil_tc_move_reg(&r[11].v, r[7].v);
L_179:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 89, 11, 11, 0, NULL);
L_180:;
    if ((int32_t)r[10].i < (int32_t)r[11].i) goto L_182;
L_181:;
    goto L_200;
L_182:;
    goto L_185;
L_183:;
    r[9].i = (int64_t)((int32_t)r[9].i + (int32_t)1);
L_184:;
    goto L_176;
L_185:;
    vigil_tc_move_reg(&r[10].v, r[7].v);
L_186:;
    vigil_tc_move_reg(&r[12].v, r[9].v);
L_187:;
    vigil_tc_move_reg(&r[11].v, r[10].v);
L_188:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 87, 10, 11, 12, NULL);
L_189:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "  filter[", 9, &_s, NULL); vigil_value_init_object(&r[13].v, &_s); }
L_190:;
    vigil_tc_move_reg(&r[14].v, r[9].v);
L_191:;
    vigil_tc_to_string(tc, &r[14].v, &r[14].v, NULL);
L_192:;
    vigil_tc_generic_add(tc, &r[15].v, &r[13].v, &r[14].v, NULL);
L_193:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "]: ", 3, &_s, NULL); vigil_value_init_object(&r[16].v, &_s); }
L_194:;
    vigil_tc_generic_add(tc, &r[17].v, &r[15].v, &r[16].v, NULL);
L_195:;
L_196:;
    vigil_tc_generic_add(tc, &r[19].v, &r[17].v, &r[10].v, NULL);
L_197:;
    vigil_tc_call_native(tc, (uint64_t *)r, 19, 1, 81, NULL);
L_199:;
    goto L_183;
L_200:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "positionals: ", 13, &_s, NULL); vigil_value_init_object(&r[9].v, &_s); }
L_201:;
    vigil_tc_move_reg(&r[10].v, r[8].v);
L_202:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 89, 10, 10, 0, NULL);
L_203:;
    vigil_tc_to_string(tc, &r[10].v, &r[10].v, NULL);
L_204:;
    vigil_tc_generic_add(tc, &r[9].v, &r[9].v, &r[10].v, NULL);
L_205:;
    vigil_tc_call_native(tc, (uint64_t *)r, 9, 1, 83, NULL);
L_207:;
    r[9].i = (int64_t)0LL;
L_208:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 126, 10, 0, 0, NULL);
L_209:;
    vigil_tc_move_reg(&r[10].v, r[9].v);
L_210:;
    vigil_tc_move_reg(&r[12].v, r[8].v);
L_211:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 89, 12, 12, 0, NULL);
L_212:;
    if ((int32_t)r[10].i < (int32_t)r[12].i) goto L_214;
L_213:;
    goto L_232;
L_214:;
    goto L_217;
L_215:;
    r[9].i = (int64_t)((int32_t)r[9].i + (int32_t)1);
L_216:;
    goto L_208;
L_217:;
    vigil_tc_move_reg(&r[10].v, r[8].v);
L_218:;
    vigil_tc_move_reg(&r[13].v, r[9].v);
L_219:;
    vigil_tc_move_reg(&r[12].v, r[10].v);
L_220:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 87, 10, 12, 13, NULL);
L_221:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "  pos[", 6, &_s, NULL); vigil_value_init_object(&r[14].v, &_s); }
L_222:;
    vigil_tc_move_reg(&r[15].v, r[9].v);
L_223:;
    vigil_tc_to_string(tc, &r[15].v, &r[15].v, NULL);
L_224:;
    vigil_tc_generic_add(tc, &r[16].v, &r[14].v, &r[15].v, NULL);
L_225:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "]:    ", 6, &_s, NULL); vigil_value_init_object(&r[17].v, &_s); }
L_226:;
    vigil_tc_generic_add(tc, &r[18].v, &r[16].v, &r[17].v, NULL);
L_227:;
L_228:;
    vigil_tc_generic_add(tc, &r[20].v, &r[18].v, &r[10].v, NULL);
L_229:;
    vigil_tc_call_native(tc, (uint64_t *)r, 20, 1, 88, NULL);
L_231:;
    goto L_215;
L_232:;
    r[9].i = (int64_t)0LL;
L_233:;
L_234:;
    tc->ret_count = 1;
    return r[9];
    return (vigil_reg_t){0};
}

