/* Generated by vigil transpile — do not edit. */
#include "vigil_generated.h"
#include <math.h>
#include <string.h>
#include "vigil/transpile_rt.h"
#include "vigil/value.h"

vigil_value_t *vigil_fn_constants[3];
size_t vigil_fn_constant_counts[3];

static vigil_reg_t vigil_fn_0(vigil_tc_t *tc, vigil_reg_t arg_0);
static vigil_reg_t vigil_fn_1(vigil_tc_t *tc);
vigil_reg_t vigil_fn_2(vigil_tc_t *tc);

vigil_reg_t vigil_fn_0(vigil_tc_t *tc, vigil_reg_t arg_0)
{
    vigil_reg_t r[3];
    memset(r, 0, sizeof(r));
    r[0] = arg_0;
    tc->constants = vigil_fn_constants[0];
    tc->constant_count = vigil_fn_constant_counts[0];

L_0:;
    vigil_tc_move_reg(&r[1].v, r[0].v);
L_1:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "hello", 5, &_s, NULL); vigil_value_init_object(&r[2].v, &_s); }
L_2:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 84, 1, 0, 2, NULL);
L_3:;
    tc->ret_count = 0;
    return (vigil_reg_t){0};
    return (vigil_reg_t){0};
}

vigil_reg_t vigil_fn_1(vigil_tc_t *tc)
{
    vigil_reg_t r[4];
    memset(r, 0, sizeof(r));
    tc->constants = vigil_fn_constants[1];
    tc->constant_count = vigil_fn_constant_counts[1];

L_0:;
    r[1].i = 0;
L_1:;
    { uint16_t _ci = 0; uint8_t _fb = 1, _fc = 1;
      vigil_tc_new_instance(tc, (uint64_t *)r, 2, _ci, _fb, _fc, NULL); }
L_3:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 125, 3, 2, 0, NULL);
L_4:;
    { const vigil_value_t *_sc = tc->constants; size_t _sn = tc->constant_count;
    r[3] = vigil_fn_0(tc, r[3]);
    { uint8_t _ri; for (_ri = 1; _ri < tc->ret_count; _ri++) r[3 + _ri].v = tc->ret_buf[_ri]; }
    tc->constants = _sc; tc->constant_count = _sn; }
L_5:;
L_6:;
    tc->ret_count = 1;
    return r[2];
    return (vigil_reg_t){0};
}

vigil_reg_t vigil_fn_2(vigil_tc_t *tc)
{
    vigil_reg_t r[3];
    memset(r, 0, sizeof(r));
    tc->constants = vigil_fn_constants[2];
    tc->constant_count = vigil_fn_constant_counts[2];

L_0:;
    { const vigil_value_t *_sc = tc->constants; size_t _sn = tc->constant_count;
    r[0] = vigil_fn_1(tc);
    { uint8_t _ri; for (_ri = 1; _ri < tc->ret_count; _ri++) r[0 + _ri].v = tc->ret_buf[_ri]; }
    tc->constants = _sc; tc->constant_count = _sn; }
L_1:;
    vigil_tc_move_reg(&r[1].v, r[0].v);
L_2:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 83, 1, 1, 0, NULL);
L_3:;
    vigil_tc_call_native(tc, (uint64_t *)r, 1, 1, 0, NULL);
L_5:;
    r[2].i = (int64_t)0LL;
L_6:;
L_7:;
    tc->ret_count = 1;
    return r[2];
    return (vigil_reg_t){0};
}

