FROM emscripten/emsdk:latest

RUN apt-get update && apt-get install -y --no-install-recommends cmake && rm -rf /var/lib/apt/lists/*

WORKDIR /vigil
COPY . .

RUN emcmake cmake -S . -B build \
      -DVIGIL_BUILD_TESTS=ON \
      -DVIGIL_PLUGIN_SDL=ON \
      -DVIGIL_PLUGIN_GUI=ON \
      -DVIGIL_PLUGIN_AUDIO=ON \
      -DVIGIL_PLUGIN_SYSQUERY=ON \
      -DCMAKE_BUILD_TYPE=Release \
      -DCMAKE_C_FLAGS="-pthread" \
      -DCMAKE_EXE_LINKER_FLAGS="-pthread -sUSE_PTHREADS=1 -lwebsocket.js -sEXIT_RUNTIME=1 -sALLOW_MEMORY_GROWTH=1 -sNODERAWFS=1" && \
    cmake --build build

CMD ["node", "build/vigil_tests.js"]
