/* Generated by vigil transpile — do not edit. */
#include "vigil_generated.h"
#include <math.h>
#include <string.h>
#include "vigil/transpile_rt.h"
#include "vigil/value.h"

vigil_value_t *vigil_fn_constants[6];
size_t vigil_fn_constant_counts[6];

vigil_reg_t vigil_fn_0(vigil_tc_t *tc);
static vigil_reg_t vigil_fn_1(vigil_tc_t *tc);
static vigil_reg_t vigil_fn_2(vigil_tc_t *tc);
static vigil_reg_t vigil_fn_3(vigil_tc_t *tc);
static vigil_reg_t vigil_fn_4(vigil_tc_t *tc);
static vigil_reg_t vigil_fn_5(vigil_tc_t *tc);

vigil_reg_t vigil_fn_0(vigil_tc_t *tc)
{
    vigil_reg_t r[17];
    memset(r, 0, sizeof(r));
    tc->constants = vigil_fn_constants[0];
    tc->constant_count = vigil_fn_constant_counts[0];

L_0:;
    r[0].i = (int64_t)0LL;
L_1:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 77, 0, 0, 0, NULL);
L_2:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "Starting concurrent counter example", 35, &_s, NULL); vigil_value_init_object(&r[0].v, &_s); }
L_3:;
    vigil_tc_call_native(tc, (uint64_t *)r, 0, 1, 2, NULL);
L_5:;
    vigil_tc_call_native(tc, (uint64_t *)r, 0, 0, 3, NULL);
L_7:;
    vigil_tc_move_reg(&r[1].v, r[0].v);
L_8:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 81, 1, 1, 1, NULL);
L_9:;
    vigil_tc_call_native(tc, (uint64_t *)r, 1, 1, 4, NULL);
L_11:;
    vigil_tc_move_reg(&r[2].v, r[0].v);
L_12:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 81, 2, 2, 1, NULL);
L_13:;
    vigil_tc_call_native(tc, (uint64_t *)r, 2, 1, 5, NULL);
L_15:;
    vigil_tc_move_reg(&r[3].v, r[0].v);
L_16:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 81, 3, 3, 1, NULL);
L_17:;
    vigil_tc_call_native(tc, (uint64_t *)r, 3, 1, 6, NULL);
L_19:;
    vigil_tc_move_reg(&r[4].v, r[0].v);
L_20:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 81, 4, 4, 1, NULL);
L_21:;
    vigil_tc_call_native(tc, (uint64_t *)r, 4, 1, 7, NULL);
L_23:;
    vigil_tc_move_reg(&r[5].v, r[0].v);
L_24:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 81, 5, 5, 1, NULL);
L_25:;
    vigil_tc_call_native(tc, (uint64_t *)r, 5, 1, 8, NULL);
L_27:;
    vigil_tc_move_reg(&r[6].v, r[1].v);
L_28:;
    vigil_tc_call_native(tc, (uint64_t *)r, 6, 1, 9, NULL);
L_30:;
    vigil_tc_move_reg(&r[7].v, r[2].v);
L_31:;
    vigil_tc_call_native(tc, (uint64_t *)r, 7, 1, 10, NULL);
L_33:;
    vigil_tc_move_reg(&r[8].v, r[3].v);
L_34:;
    vigil_tc_call_native(tc, (uint64_t *)r, 8, 1, 11, NULL);
L_36:;
    vigil_tc_move_reg(&r[9].v, r[4].v);
L_37:;
    vigil_tc_call_native(tc, (uint64_t *)r, 9, 1, 12, NULL);
L_39:;
    vigil_tc_move_reg(&r[10].v, r[5].v);
L_40:;
    vigil_tc_call_native(tc, (uint64_t *)r, 10, 1, 13, NULL);
L_42:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "Final counter value: ", 21, &_s, NULL); vigil_value_init_object(&r[11].v, &_s); }
L_43:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 76, 12, 0, 0, NULL);
L_44:;
    vigil_tc_to_string(tc, &r[12].v, &r[12].v, NULL);
L_45:;
    vigil_tc_generic_add(tc, &r[13].v, &r[11].v, &r[12].v, NULL);
L_46:;
    vigil_tc_call_native(tc, (uint64_t *)r, 13, 1, 15, NULL);
L_48:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "Expected: 5000", 14, &_s, NULL); vigil_value_init_object(&r[14].v, &_s); }
L_49:;
    vigil_tc_call_native(tc, (uint64_t *)r, 14, 1, 17, NULL);
L_51:;
    vigil_tc_move_reg(&r[15].v, r[0].v);
L_52:;
    vigil_tc_call_native(tc, (uint64_t *)r, 15, 1, 18, NULL);
L_54:;
    r[16].i = (int64_t)0LL;
L_55:;
L_56:;
    tc->ret_count = 1;
    return r[16];
    return (vigil_reg_t){0};
}

vigil_reg_t vigil_fn_1(vigil_tc_t *tc)
{
    vigil_reg_t r[8];
    memset(r, 0, sizeof(r));
    tc->constants = vigil_fn_constants[1];
    tc->constant_count = vigil_fn_constant_counts[1];

L_0:;
    r[0].i = (int64_t)0LL;
L_1:;
    vigil_tc_move_reg(&r[1].v, r[0].v);
L_2:;
    r[2].i = (int64_t)1000LL;
L_3:;
    if ((int32_t)r[1].i < (int32_t)r[2].i) goto L_5;
L_4:;
    goto L_18;
L_5:;
    goto L_8;
L_6:;
    r[0].i = (int64_t)((int32_t)r[0].i + (int32_t)1);
L_7:;
    goto L_1;
L_8:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 78, 3, 0, 0, NULL);
L_9:;
    vigil_tc_call_native(tc, (uint64_t *)r, 3, 1, 3, NULL);
L_11:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 76, 4, 0, 0, NULL);
L_12:;
    r[6].i = (int64_t)((int32_t)r[4].i + (int32_t)1);
L_13:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 77, 6, 0, 0, NULL);
L_14:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 78, 7, 0, 0, NULL);
L_15:;
    vigil_tc_call_native(tc, (uint64_t *)r, 7, 1, 5, NULL);
L_17:;
    goto L_6;
L_18:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "Thread 1 finished", 17, &_s, NULL); vigil_value_init_object(&r[0].v, &_s); }
L_19:;
    vigil_tc_call_native(tc, (uint64_t *)r, 0, 1, 7, NULL);
L_21:;
    tc->ret_count = 0;
    return (vigil_reg_t){0};
    return (vigil_reg_t){0};
}

vigil_reg_t vigil_fn_2(vigil_tc_t *tc)
{
    vigil_reg_t r[8];
    memset(r, 0, sizeof(r));
    tc->constants = vigil_fn_constants[2];
    tc->constant_count = vigil_fn_constant_counts[2];

L_0:;
    r[0].i = (int64_t)0LL;
L_1:;
    vigil_tc_move_reg(&r[1].v, r[0].v);
L_2:;
    r[2].i = (int64_t)1000LL;
L_3:;
    if ((int32_t)r[1].i < (int32_t)r[2].i) goto L_5;
L_4:;
    goto L_18;
L_5:;
    goto L_8;
L_6:;
    r[0].i = (int64_t)((int32_t)r[0].i + (int32_t)1);
L_7:;
    goto L_1;
L_8:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 78, 3, 0, 0, NULL);
L_9:;
    vigil_tc_call_native(tc, (uint64_t *)r, 3, 1, 3, NULL);
L_11:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 76, 4, 0, 0, NULL);
L_12:;
    r[6].i = (int64_t)((int32_t)r[4].i + (int32_t)1);
L_13:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 77, 6, 0, 0, NULL);
L_14:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 78, 7, 0, 0, NULL);
L_15:;
    vigil_tc_call_native(tc, (uint64_t *)r, 7, 1, 5, NULL);
L_17:;
    goto L_6;
L_18:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "Thread 2 finished", 17, &_s, NULL); vigil_value_init_object(&r[0].v, &_s); }
L_19:;
    vigil_tc_call_native(tc, (uint64_t *)r, 0, 1, 7, NULL);
L_21:;
    tc->ret_count = 0;
    return (vigil_reg_t){0};
    return (vigil_reg_t){0};
}

vigil_reg_t vigil_fn_3(vigil_tc_t *tc)
{
    vigil_reg_t r[8];
    memset(r, 0, sizeof(r));
    tc->constants = vigil_fn_constants[3];
    tc->constant_count = vigil_fn_constant_counts[3];

L_0:;
    r[0].i = (int64_t)0LL;
L_1:;
    vigil_tc_move_reg(&r[1].v, r[0].v);
L_2:;
    r[2].i = (int64_t)1000LL;
L_3:;
    if ((int32_t)r[1].i < (int32_t)r[2].i) goto L_5;
L_4:;
    goto L_18;
L_5:;
    goto L_8;
L_6:;
    r[0].i = (int64_t)((int32_t)r[0].i + (int32_t)1);
L_7:;
    goto L_1;
L_8:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 78, 3, 0, 0, NULL);
L_9:;
    vigil_tc_call_native(tc, (uint64_t *)r, 3, 1, 3, NULL);
L_11:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 76, 4, 0, 0, NULL);
L_12:;
    r[6].i = (int64_t)((int32_t)r[4].i + (int32_t)1);
L_13:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 77, 6, 0, 0, NULL);
L_14:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 78, 7, 0, 0, NULL);
L_15:;
    vigil_tc_call_native(tc, (uint64_t *)r, 7, 1, 5, NULL);
L_17:;
    goto L_6;
L_18:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "Thread 3 finished", 17, &_s, NULL); vigil_value_init_object(&r[0].v, &_s); }
L_19:;
    vigil_tc_call_native(tc, (uint64_t *)r, 0, 1, 7, NULL);
L_21:;
    tc->ret_count = 0;
    return (vigil_reg_t){0};
    return (vigil_reg_t){0};
}

vigil_reg_t vigil_fn_4(vigil_tc_t *tc)
{
    vigil_reg_t r[8];
    memset(r, 0, sizeof(r));
    tc->constants = vigil_fn_constants[4];
    tc->constant_count = vigil_fn_constant_counts[4];

L_0:;
    r[0].i = (int64_t)0LL;
L_1:;
    vigil_tc_move_reg(&r[1].v, r[0].v);
L_2:;
    r[2].i = (int64_t)1000LL;
L_3:;
    if ((int32_t)r[1].i < (int32_t)r[2].i) goto L_5;
L_4:;
    goto L_18;
L_5:;
    goto L_8;
L_6:;
    r[0].i = (int64_t)((int32_t)r[0].i + (int32_t)1);
L_7:;
    goto L_1;
L_8:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 78, 3, 0, 0, NULL);
L_9:;
    vigil_tc_call_native(tc, (uint64_t *)r, 3, 1, 3, NULL);
L_11:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 76, 4, 0, 0, NULL);
L_12:;
    r[6].i = (int64_t)((int32_t)r[4].i + (int32_t)1);
L_13:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 77, 6, 0, 0, NULL);
L_14:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 78, 7, 0, 0, NULL);
L_15:;
    vigil_tc_call_native(tc, (uint64_t *)r, 7, 1, 5, NULL);
L_17:;
    goto L_6;
L_18:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "Thread 4 finished", 17, &_s, NULL); vigil_value_init_object(&r[0].v, &_s); }
L_19:;
    vigil_tc_call_native(tc, (uint64_t *)r, 0, 1, 7, NULL);
L_21:;
    tc->ret_count = 0;
    return (vigil_reg_t){0};
    return (vigil_reg_t){0};
}

vigil_reg_t vigil_fn_5(vigil_tc_t *tc)
{
    vigil_reg_t r[8];
    memset(r, 0, sizeof(r));
    tc->constants = vigil_fn_constants[5];
    tc->constant_count = vigil_fn_constant_counts[5];

L_0:;
    r[0].i = (int64_t)0LL;
L_1:;
    vigil_tc_move_reg(&r[1].v, r[0].v);
L_2:;
    r[2].i = (int64_t)1000LL;
L_3:;
    if ((int32_t)r[1].i < (int32_t)r[2].i) goto L_5;
L_4:;
    goto L_18;
L_5:;
    goto L_8;
L_6:;
    r[0].i = (int64_t)((int32_t)r[0].i + (int32_t)1);
L_7:;
    goto L_1;
L_8:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 78, 3, 0, 0, NULL);
L_9:;
    vigil_tc_call_native(tc, (uint64_t *)r, 3, 1, 3, NULL);
L_11:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 76, 4, 0, 0, NULL);
L_12:;
    r[6].i = (int64_t)((int32_t)r[4].i + (int32_t)1);
L_13:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 77, 6, 0, 0, NULL);
L_14:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 78, 7, 0, 0, NULL);
L_15:;
    vigil_tc_call_native(tc, (uint64_t *)r, 7, 1, 5, NULL);
L_17:;
    goto L_6;
L_18:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "Thread 5 finished", 17, &_s, NULL); vigil_value_init_object(&r[0].v, &_s); }
L_19:;
    vigil_tc_call_native(tc, (uint64_t *)r, 0, 1, 7, NULL);
L_21:;
    tc->ret_count = 0;
    return (vigil_reg_t){0};
    return (vigil_reg_t){0};
}

