/* vigil_image_test.c — Unit tests for the stb_image wrapper. */
#include "vigil_test.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* Include the wrapper header directly — the test links against the SDL plugin. */
#include "../../plugins/sdl/vigil_image.h"

/* Minimal 1x1 red RGBA PNG generated by Python zlib. */
static const unsigned char kTestPng[] = {
    0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A, 0x00, 0x00, 0x00, 0x0D, 0x49, 0x48, 0x44, 0x52, 0x00, 0x00,
    0x00, 0x01, 0x00, 0x00, 0x00, 0x01, 0x08, 0x06, 0x00, 0x00, 0x00, 0x1F, 0x15, 0xC4, 0x89, 0x00, 0x00, 0x00,
    0x0D, 0x49, 0x44, 0x41, 0x54, 0x78, 0x9C, 0x63, 0xF8, 0xCF, 0xC0, 0xF0, 0x1F, 0x00, 0x05, 0x00, 0x01, 0xFF,
    0x89, 0x99, 0x3D, 0x1D, 0x00, 0x00, 0x00, 0x00, 0x49, 0x45, 0x4E, 0x44, 0xAE, 0x42, 0x60, 0x82,
};

TEST(VigilImageTest, LoadFromMemoryDecodesValidPng)
{
    vigil_image_t img;
    memset(&img, 0, sizeof(img));

    /* Write the PNG to a temp file and load it. */
    int result = vigil_image_load_memory(kTestPng, sizeof(kTestPng), &img);
    EXPECT_EQ(result, 0);
    EXPECT_EQ(img.width, 1);
    EXPECT_EQ(img.height, 1);
    EXPECT_EQ(img.channels, 4);
    EXPECT_NE(img.pixels, NULL);

    vigil_image_free(&img);
    EXPECT_EQ(img.pixels, NULL);
}

TEST(VigilImageTest, LoadFromMemoryRejectsInvalidData)
{
    vigil_image_t img;
    unsigned char garbage[] = {0x00, 0x01, 0x02, 0x03};

    int result = vigil_image_load_memory(garbage, sizeof(garbage), &img);
    EXPECT_EQ(result, -1);
    EXPECT_EQ(img.pixels, NULL);
}

TEST(VigilImageTest, LoadFromMemoryRejectsNullInput)
{
    vigil_image_t img;

    EXPECT_EQ(vigil_image_load_memory(NULL, 0, &img), -1);
    EXPECT_EQ(vigil_image_load_memory(kTestPng, sizeof(kTestPng), NULL), -1);
    EXPECT_EQ(vigil_image_load_memory(kTestPng, 0, &img), -1);
}

TEST(VigilImageTest, LoadFromFileDecodesWrittenPng)
{
    vigil_image_t img;
    const char *path = "/tmp/vigil_image_test.png";

    /* Write the test PNG to disk. */
    FILE *f = fopen(path, "wb");
    ASSERT_NE(f, NULL);
    fwrite(kTestPng, 1, sizeof(kTestPng), f);
    fclose(f);

    int result = vigil_image_load_file(path, &img);
    EXPECT_EQ(result, 0);
    EXPECT_EQ(img.width, 1);
    EXPECT_EQ(img.height, 1);
    EXPECT_EQ(img.channels, 4);
    EXPECT_NE(img.pixels, NULL);

    vigil_image_free(&img);
    remove(path);
}

TEST(VigilImageTest, LoadFromFileRejectsNonexistent)
{
    vigil_image_t img;
    EXPECT_EQ(vigil_image_load_file("/tmp/nonexistent_vigil_test.xyz", &img), -1);
    EXPECT_EQ(img.pixels, NULL);
}

TEST(VigilImageTest, FreeHandlesNullSafely)
{
    vigil_image_t img;
    memset(&img, 0, sizeof(img));
    vigil_image_free(&img); /* should not crash */
    vigil_image_free(NULL); /* should not crash */
    EXPECT_EQ(img.pixels, NULL);
}

void register_image_tests(void)
{
    REGISTER_TEST(VigilImageTest, LoadFromMemoryDecodesValidPng);
    REGISTER_TEST(VigilImageTest, LoadFromMemoryRejectsInvalidData);
    REGISTER_TEST(VigilImageTest, LoadFromMemoryRejectsNullInput);
    REGISTER_TEST(VigilImageTest, LoadFromFileDecodesWrittenPng);
    REGISTER_TEST(VigilImageTest, LoadFromFileRejectsNonexistent);
    REGISTER_TEST(VigilImageTest, FreeHandlesNullSafely);
}
