/* Generated by vigil transpile — do not edit. */
#ifndef VIGIL_GENERATED_H
#define VIGIL_GENERATED_H
#include <stdint.h>
#include <stddef.h>
typedef union vigil_reg { int64_t i; double f; uint64_t v; } vigil_reg_t;
struct vigil_tc;
extern uint64_t *vigil_fn_constants[24];
extern size_t vigil_fn_constant_counts[24];
vigil_reg_t vigil_fn_23(struct vigil_tc *tc);
#endif
