/* Generated by vigil transpile -- do not edit. */
#include "vigil_generated.h"
#include <stdio.h>
#include <stdlib.h>
#include "vigil/transpile_rt.h"
#include "vigil/vigil.h"
#include "vigil/stdlib.h"
#include "vigil/compiler.h"
#include "internal/vigil_internal.h"
#include "plugin_registry.h"

static const char vigil_src_0[] = "import \"args\"\nimport \"fmt\"\n\nfn main() -> i32 {\n    // Create argument parser using the builder pattern\n    args.Parser parser = args.Parser.new(\"mytool\", \"A simple CLI tool example\").flag(\"verbose\", \"v\", \"Enable verbose output\").option(\"output\", \"o\", \"Output file path\", \"\").option_int(\"count\", \"c\", \"Number of iterations\", \"1\").positional(\"input\", \"Input file path\")\n    // Check for --help before parsing\n    for (i32 i = 0; i < args.count(); i++) {\n        string a = args.at(i)\n        if a == \"--help\" || a == \"-h\" {\n            fmt.println(parser.help())\n            return 0\n        }\n\n    }\n\n    // Parse arguments\n    err e = parser.parse(0)\n    if e != ok {\n        fmt.println(f\"Error: {e.message()}\")\n        fmt.println(parser.help())\n        return 1\n    }\n\n    // Get parsed values\n    bool verbose = parser.get_bool(\"verbose\")\n    string output = parser.get(\"output\")\n    string countStr = parser.get(\"count\")\n    array<string> positionals = parser.get_positionals()\n    string input = \"\"\n    if positionals.len() > 0 {\n        input = positionals[0]\n    }\n\n    // Display parsed values\n    fmt.println(\"Parsed arguments:\")\n    fmt.println(f\"  Input: {input}\")\n    fmt.println(f\"  Output: {output}\")\n    fmt.println(f\"  Count: {countStr}\")\n    fmt.println(f\"  Verbose: {verbose}\")\n    if verbose {\n        fmt.println(\"\\nVerbose mode enabled!\")\n        fmt.println(f\"Processing {input} {countStr} times...\")\n    }\n\n    return 0\n}\n";
static const char vigil_path_0[] = "examples/cli_tool.vigil";

int main(void)
{
    vigil_runtime_t *runtime = NULL;
    vigil_vm_t *vm = NULL;
    vigil_error_t error = {0};
    vigil_source_registry_t registry;
    vigil_diagnostic_list_t diagnostics;
    vigil_object_t *function = NULL;
    vigil_source_id_t sid = 0;
    vigil_tc_t tc = {0};
    if (vigil_runtime_open(&runtime, NULL, &error) != 0) return 1;
    if (vigil_vm_open(&vm, runtime, NULL, &error) != 0)
    { vigil_runtime_close(&runtime); return 1; }
    vigil_vm_set_aot_enabled(vm, 0);
    vigil_source_registry_init(&registry, runtime);
    vigil_diagnostic_list_init(&diagnostics, runtime);
    { vigil_source_id_t _id = 0;
      vigil_source_registry_register_cstr(&registry, vigil_path_0, vigil_src_0, &_id, &error);
      if (0 == 0) sid = _id; }
    { vigil_native_registry_t natives;
      vigil_native_registry_init(&natives);
      vigil_stdlib_register_all(&natives, &error);
      vigil_plugin_register_all(&natives, &error);
      vigil_compile_source_with_natives(&registry, sid, &natives, &function, &diagnostics, &error);
      vigil_native_registry_free(&natives); }
    if (!function) { vigil_diagnostic_list_free(&diagnostics);
      vigil_source_registry_free(&registry); vigil_vm_close(&vm);
      vigil_runtime_close(&runtime); return 1; }
    tc.vm = vm; tc.runtime = runtime;
    tc.function = function;
    { size_t _fi;
      for (_fi = 0; _fi < 1; _fi++) {
        const vigil_object_t *_fn = vigil_function_object_sibling(function, _fi);
        if (!_fn) _fn = function;
        const vigil_chunk_t *_ch = vigil_function_object_chunk(_fn);
        vigil_fn_constants[_fi] = _ch ? (vigil_value_t*)vigil_chunk_constant(_ch, 0) : NULL;
        vigil_fn_constant_counts[_fi] = _ch ? vigil_chunk_constant_count(_ch) : 0;
      }
    }
    tc.constants = vigil_fn_constants[0];
    tc.constant_count = vigil_fn_constant_counts[0];
    vigil_reg_t result = vigil_fn_0(&tc);
    vigil_vm_close(&vm);
    vigil_object_release(&function);
    vigil_diagnostic_list_free(&diagnostics);
    vigil_source_registry_free(&registry);
    vigil_runtime_close(&runtime);
    return (int)result.i;
}
