/* Generated by vigil transpile — do not edit. */
#include "vigil_generated.h"
#include <math.h>
#include <string.h>
#include "vigil/transpile_rt.h"
#include "vigil/value.h"

vigil_value_t *vigil_fn_constants[1];
size_t vigil_fn_constant_counts[1];

vigil_reg_t vigil_fn_0(vigil_tc_t *tc);

vigil_reg_t vigil_fn_0(vigil_tc_t *tc)
{
    vigil_reg_t r[34];
    memset(r, 0, sizeof(r));
    tc->constants = vigil_fn_constants[0];
    tc->constant_count = vigil_fn_constant_counts[0];

L_0:;
    r[0].i = (int64_t)0LL;
L_1:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "mytool", 6, &_s, NULL); vigil_value_init_object(&r[1].v, &_s); }
L_2:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "A simple CLI tool example", 25, &_s, NULL); vigil_value_init_object(&r[2].v, &_s); }
L_3:;
    vigil_tc_call_native(tc, (uint64_t *)r, 0, 3, 3, NULL);
L_5:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "verbose", 7, &_s, NULL); vigil_value_init_object(&r[1].v, &_s); }
L_6:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 126, 2, 0, 0, NULL);
L_7:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "v", 1, &_s, NULL); vigil_value_init_object(&r[2].v, &_s); }
L_8:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "Enable verbose output", 21, &_s, NULL); vigil_value_init_object(&r[3].v, &_s); }
L_9:;
    vigil_tc_call_native(tc, (uint64_t *)r, 0, 4, 7, NULL);
L_11:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "output", 6, &_s, NULL); vigil_value_init_object(&r[1].v, &_s); }
L_12:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "o", 1, &_s, NULL); vigil_value_init_object(&r[2].v, &_s); }
L_13:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 126, 3, 0, 0, NULL);
L_14:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "Output file path", 16, &_s, NULL); vigil_value_init_object(&r[3].v, &_s); }
L_15:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "", 0, &_s, NULL); vigil_value_init_object(&r[4].v, &_s); }
L_16:;
    vigil_tc_call_native(tc, (uint64_t *)r, 0, 5, 12, NULL);
L_18:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "count", 5, &_s, NULL); vigil_value_init_object(&r[1].v, &_s); }
L_19:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 126, 2, 0, 0, NULL);
L_20:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "c", 1, &_s, NULL); vigil_value_init_object(&r[2].v, &_s); }
L_21:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "Number of iterations", 20, &_s, NULL); vigil_value_init_object(&r[3].v, &_s); }
L_22:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 126, 4, 0, 0, NULL);
L_23:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "1", 1, &_s, NULL); vigil_value_init_object(&r[4].v, &_s); }
L_24:;
    vigil_tc_call_native(tc, (uint64_t *)r, 0, 5, 17, NULL);
L_26:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "input", 5, &_s, NULL); vigil_value_init_object(&r[1].v, &_s); }
L_27:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "Input file path", 15, &_s, NULL); vigil_value_init_object(&r[2].v, &_s); }
L_28:;
    vigil_tc_call_native(tc, (uint64_t *)r, 0, 3, 20, NULL);
L_30:;
    r[1].i = (int64_t)0LL;
L_31:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 126, 2, 0, 0, NULL);
L_32:;
    vigil_tc_move_reg(&r[2].v, r[1].v);
L_33:;
    vigil_tc_call_native(tc, (uint64_t *)r, 3, 0, 22, NULL);
L_35:;
    if ((int32_t)r[2].i < (int32_t)r[3].i) goto L_37;
L_36:;
    goto L_65;
L_37:;
    goto L_40;
L_38:;
    r[1].i = (int64_t)((int32_t)r[1].i + (int32_t)1);
L_39:;
    goto L_31;
L_40:;
    vigil_tc_move_reg(&r[2].v, r[1].v);
L_41:;
    vigil_tc_call_native(tc, (uint64_t *)r, 2, 1, 24, NULL);
L_43:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 126, 3, 0, 0, NULL);
L_44:;
    vigil_tc_move_reg(&r[3].v, r[2].v);
L_45:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "--help", 6, &_s, NULL); vigil_value_init_object(&r[4].v, &_s); }
L_46:;
    r[3].i = vigil_tc_values_equal((uint64_t *)r, 3, 4);
L_47:;
    if (vigil_tc_is_truthy(r[3].v)) goto L_49;
L_48:;
    goto L_50;
L_49:;
    goto L_54;
L_50:;
    vigil_tc_move_reg(&r[3].v, r[2].v);
L_51:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 126, 4, 0, 0, NULL);
L_52:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "-h", 2, &_s, NULL); vigil_value_init_object(&r[4].v, &_s); }
L_53:;
    r[3].i = vigil_tc_values_equal((uint64_t *)r, 3, 4);
L_54:;
    if (vigil_tc_is_truthy(r[3].v)) goto L_56;
L_55:;
    goto L_64;
L_56:;
    vigil_tc_move_reg(&r[3].v, r[0].v);
L_57:;
    vigil_tc_call_native(tc, (uint64_t *)r, 3, 1, 27, NULL);
L_59:;
    vigil_tc_call_native(tc, (uint64_t *)r, 3, 1, 28, NULL);
L_61:;
    r[3].i = (int64_t)0LL;
L_62:;
L_63:;
    tc->ret_count = 1;
    return r[3];
L_64:;
    goto L_38;
L_65:;
    vigil_tc_move_reg(&r[1].v, r[0].v);
L_66:;
    r[2].i = (int64_t)0LL;
L_67:;
    vigil_tc_call_native(tc, (uint64_t *)r, 1, 2, 31, NULL);
L_69:;
    vigil_tc_move_reg(&r[2].v, r[1].v);
L_70:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 126, 3, 0, 0, NULL);
L_71:;
    r[3].v = vigil_value_copy(&tc->constants[32]);
L_72:;
    r[2].i = vigil_tc_values_equal((uint64_t *)r, 2, 3);
L_73:;
    r[2].i = !r[2].i;
L_74:;
    if (vigil_tc_is_truthy(r[2].v)) goto L_76;
L_75:;
    goto L_90;
L_76:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "Error: ", 7, &_s, NULL); vigil_value_init_object(&r[2].v, &_s); }
L_77:;
    vigil_tc_move_reg(&r[3].v, r[1].v);
L_78:;
    vigil_tc_get_error_msg(tc, &r[3].v, &r[3].v, NULL);
L_79:;
    vigil_tc_generic_add(tc, &r[2].v, &r[2].v, &r[3].v, NULL);
L_80:;
    vigil_tc_call_native(tc, (uint64_t *)r, 2, 1, 34, NULL);
L_82:;
    vigil_tc_move_reg(&r[2].v, r[0].v);
L_83:;
    vigil_tc_call_native(tc, (uint64_t *)r, 2, 1, 35, NULL);
L_85:;
    vigil_tc_call_native(tc, (uint64_t *)r, 2, 1, 36, NULL);
L_87:;
    r[2].i = (int64_t)1LL;
L_88:;
L_89:;
    tc->ret_count = 1;
    return r[2];
L_90:;
    vigil_tc_move_reg(&r[2].v, r[0].v);
L_91:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "verbose", 7, &_s, NULL); vigil_value_init_object(&r[3].v, &_s); }
L_92:;
    vigil_tc_call_native(tc, (uint64_t *)r, 2, 2, 39, NULL);
L_94:;
    vigil_tc_move_reg(&r[3].v, r[0].v);
L_95:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "output", 6, &_s, NULL); vigil_value_init_object(&r[4].v, &_s); }
L_96:;
    vigil_tc_call_native(tc, (uint64_t *)r, 3, 2, 41, NULL);
L_98:;
    vigil_tc_move_reg(&r[4].v, r[0].v);
L_99:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "count", 5, &_s, NULL); vigil_value_init_object(&r[5].v, &_s); }
L_100:;
    vigil_tc_call_native(tc, (uint64_t *)r, 4, 2, 43, NULL);
L_102:;
    vigil_tc_move_reg(&r[5].v, r[0].v);
L_103:;
    vigil_tc_call_native(tc, (uint64_t *)r, 5, 1, 44, NULL);
L_105:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "", 0, &_s, NULL); vigil_value_init_object(&r[6].v, &_s); }
L_106:;
    vigil_tc_move_reg(&r[7].v, r[5].v);
L_107:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 89, 7, 7, 0, NULL);
L_108:;
    r[8].i = (int64_t)0LL;
L_109:;
    if ((int32_t)r[7].i > (int32_t)r[8].i) goto L_111;
L_110:;
    goto L_116;
L_111:;
    vigil_tc_move_reg(&r[9].v, r[5].v);
L_112:;
    r[10].i = (int64_t)0LL;
L_113:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 87, 9, 9, 10, NULL);
L_114:;
    vigil_tc_move_reg(&r[6].v, r[9].v);
L_115:;
    goto L_116;
L_116:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "Parsed arguments:", 17, &_s, NULL); vigil_value_init_object(&r[9].v, &_s); }
L_117:;
    vigil_tc_call_native(tc, (uint64_t *)r, 9, 1, 49, NULL);
L_119:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "  Input: ", 9, &_s, NULL); vigil_value_init_object(&r[10].v, &_s); }
L_120:;
L_121:;
    vigil_tc_generic_add(tc, &r[12].v, &r[10].v, &r[6].v, NULL);
L_122:;
    vigil_tc_call_native(tc, (uint64_t *)r, 12, 1, 51, NULL);
L_124:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "  Output: ", 10, &_s, NULL); vigil_value_init_object(&r[13].v, &_s); }
L_125:;
L_126:;
    vigil_tc_generic_add(tc, &r[15].v, &r[13].v, &r[3].v, NULL);
L_127:;
    vigil_tc_call_native(tc, (uint64_t *)r, 15, 1, 53, NULL);
L_129:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "  Count: ", 9, &_s, NULL); vigil_value_init_object(&r[16].v, &_s); }
L_130:;
L_131:;
    vigil_tc_generic_add(tc, &r[18].v, &r[16].v, &r[4].v, NULL);
L_132:;
    vigil_tc_call_native(tc, (uint64_t *)r, 18, 1, 55, NULL);
L_134:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "  Verbose: ", 11, &_s, NULL); vigil_value_init_object(&r[19].v, &_s); }
L_135:;
    vigil_tc_move_reg(&r[20].v, r[2].v);
L_136:;
    vigil_tc_to_string(tc, &r[20].v, &r[20].v, NULL);
L_137:;
    vigil_tc_generic_add(tc, &r[21].v, &r[19].v, &r[20].v, NULL);
L_138:;
    vigil_tc_call_native(tc, (uint64_t *)r, 21, 1, 57, NULL);
L_140:;
L_141:;
    if (vigil_tc_is_truthy(r[2].v)) goto L_143;
L_142:;
    goto L_158;
L_143:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "\nVerbose mode enabled!", 22, &_s, NULL); vigil_value_init_object(&r[23].v, &_s); }
L_144:;
    vigil_tc_call_native(tc, (uint64_t *)r, 23, 1, 59, NULL);
L_146:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "Processing ", 11, &_s, NULL); vigil_value_init_object(&r[24].v, &_s); }
L_147:;
L_148:;
    vigil_tc_generic_add(tc, &r[26].v, &r[24].v, &r[6].v, NULL);
L_149:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, " ", 1, &_s, NULL); vigil_value_init_object(&r[27].v, &_s); }
L_150:;
    vigil_tc_generic_add(tc, &r[28].v, &r[26].v, &r[27].v, NULL);
L_151:;
L_152:;
    vigil_tc_generic_add(tc, &r[30].v, &r[28].v, &r[4].v, NULL);
L_153:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, " times...", 9, &_s, NULL); vigil_value_init_object(&r[31].v, &_s); }
L_154:;
    vigil_tc_generic_add(tc, &r[32].v, &r[30].v, &r[31].v, NULL);
L_155:;
    vigil_tc_call_native(tc, (uint64_t *)r, 32, 1, 63, NULL);
L_157:;
    goto L_158;
L_158:;
    r[33].i = (int64_t)0LL;
L_159:;
L_160:;
    tc->ret_count = 1;
    return r[33];
    return (vigil_reg_t){0};
}

