/* Generated by vigil transpile — do not edit. */
#include "vigil_generated.h"
#include <math.h>
#include <string.h>
#include "vigil/transpile_rt.h"
#include "vigil/value.h"

vigil_value_t *vigil_fn_constants[1];
size_t vigil_fn_constant_counts[1];

vigil_reg_t vigil_fn_0(vigil_tc_t *tc);

vigil_reg_t vigil_fn_0(vigil_tc_t *tc)
{
    vigil_reg_t r[15];
    memset(r, 0, sizeof(r));
    tc->constants = vigil_fn_constants[0];
    tc->constant_count = vigil_fn_constant_counts[0];

L_0:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "Hello from VIGIL!\nThis is line 2.\n", 34, &_s, NULL); vigil_value_init_object(&r[0].v, &_s); }
L_1:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "test.txt", 8, &_s, NULL); vigil_value_init_object(&r[1].v, &_s); }
L_2:;
    vigil_tc_move_reg(&r[2].v, r[0].v);
L_3:;
    vigil_tc_call_native(tc, (uint64_t *)r, 1, 2, 2, NULL);
L_5:;
L_6:;
    r[2].i = !r[1].i;
L_7:;
    if (vigil_tc_is_truthy(r[2].v)) goto L_9;
L_8:;
    goto L_15;
L_9:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "Error writing file", 18, &_s, NULL); vigil_value_init_object(&r[2].v, &_s); }
L_10:;
    vigil_tc_call_native(tc, (uint64_t *)r, 2, 1, 4, NULL);
L_12:;
    r[2].i = (int64_t)1LL;
L_13:;
L_14:;
    tc->ret_count = 1;
    return r[2];
L_15:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "File written successfully", 25, &_s, NULL); vigil_value_init_object(&r[2].v, &_s); }
L_16:;
    vigil_tc_call_native(tc, (uint64_t *)r, 2, 1, 7, NULL);
L_18:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "test.txt", 8, &_s, NULL); vigil_value_init_object(&r[2].v, &_s); }
L_19:;
    vigil_tc_call_native(tc, (uint64_t *)r, 2, 1, 9, NULL);
L_21:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "File contents:\n", 15, &_s, NULL); vigil_value_init_object(&r[3].v, &_s); }
L_22:;
L_23:;
    vigil_tc_generic_add(tc, &r[3].v, &r[3].v, &r[2].v, NULL);
L_24:;
    vigil_tc_call_native(tc, (uint64_t *)r, 3, 1, 11, NULL);
L_26:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "test.txt", 8, &_s, NULL); vigil_value_init_object(&r[3].v, &_s); }
L_27:;
    vigil_tc_call_native(tc, (uint64_t *)r, 3, 1, 13, NULL);
L_29:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 126, 4, 0, 0, NULL);
L_30:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "File exists: ", 13, &_s, NULL); vigil_value_init_object(&r[4].v, &_s); }
L_31:;
    vigil_tc_move_reg(&r[5].v, r[3].v);
L_32:;
    vigil_tc_to_string(tc, &r[5].v, &r[5].v, NULL);
L_33:;
    vigil_tc_generic_add(tc, &r[4].v, &r[4].v, &r[5].v, NULL);
L_34:;
    vigil_tc_call_native(tc, (uint64_t *)r, 4, 1, 15, NULL);
L_36:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "test.txt", 8, &_s, NULL); vigil_value_init_object(&r[4].v, &_s); }
L_37:;
    vigil_tc_call_native(tc, (uint64_t *)r, 4, 1, 17, NULL);
L_39:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 126, 5, 0, 0, NULL);
L_40:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "test.txt", 8, &_s, NULL); vigil_value_init_object(&r[5].v, &_s); }
L_41:;
    vigil_tc_call_native(tc, (uint64_t *)r, 5, 1, 19, NULL);
L_43:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "File size: ", 11, &_s, NULL); vigil_value_init_object(&r[6].v, &_s); }
L_44:;
    vigil_tc_move_reg(&r[7].v, r[4].v);
L_45:;
    vigil_tc_to_string(tc, &r[7].v, &r[7].v, NULL);
L_46:;
    vigil_tc_generic_add(tc, &r[6].v, &r[6].v, &r[7].v, NULL);
L_47:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 126, 7, 0, 0, NULL);
L_48:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, " bytes", 6, &_s, NULL); vigil_value_init_object(&r[7].v, &_s); }
L_49:;
    vigil_tc_generic_add(tc, &r[6].v, &r[6].v, &r[7].v, NULL);
L_50:;
    vigil_tc_call_native(tc, (uint64_t *)r, 6, 1, 22, NULL);
L_52:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "Is directory: ", 14, &_s, NULL); vigil_value_init_object(&r[6].v, &_s); }
L_53:;
    vigil_tc_move_reg(&r[7].v, r[5].v);
L_54:;
    vigil_tc_to_string(tc, &r[7].v, &r[7].v, NULL);
L_55:;
    vigil_tc_generic_add(tc, &r[6].v, &r[6].v, &r[7].v, NULL);
L_56:;
    vigil_tc_call_native(tc, (uint64_t *)r, 6, 1, 24, NULL);
L_58:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, ".", 1, &_s, NULL); vigil_value_init_object(&r[6].v, &_s); }
L_59:;
    vigil_tc_call_native(tc, (uint64_t *)r, 6, 1, 26, NULL);
L_61:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 126, 7, 0, 0, NULL);
L_62:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "\nFiles in current directory:", 28, &_s, NULL); vigil_value_init_object(&r[7].v, &_s); }
L_63:;
    vigil_tc_call_native(tc, (uint64_t *)r, 7, 1, 28, NULL);
L_65:;
    vigil_tc_move_reg(&r[7].v, r[6].v);
L_66:;
    r[8].i = (int64_t)0LL;
L_67:;
    vigil_tc_move_reg(&r[9].v, r[8].v);
L_68:;
    vigil_tc_move_reg(&r[10].v, r[7].v);
L_69:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 89, 10, 10, 0, NULL);
L_70:;
    r[9].i = (r[9].i < r[10].i);
L_71:;
    if (vigil_tc_is_truthy(r[9].v)) goto L_73;
L_72:;
    goto L_89;
L_73:;
    goto L_79;
L_74:;
    vigil_tc_move_reg(&r[9].v, r[8].v);
L_75:;
    r[11].i = (int64_t)1LL;
L_76:;
    vigil_tc_generic_add(tc, &r[9].v, &r[9].v, &r[11].v, NULL);
L_77:;
    vigil_tc_move_reg(&r[8].v, r[9].v);
L_78:;
    goto L_67;
L_79:;
    vigil_tc_move_reg(&r[9].v, r[7].v);
L_80:;
    vigil_tc_move_reg(&r[11].v, r[8].v);
L_81:;
    vigil_tc_move_reg(&r[10].v, r[9].v);
L_82:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 87, 9, 10, 11, NULL);
L_83:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "  - ", 4, &_s, NULL); vigil_value_init_object(&r[12].v, &_s); }
L_84:;
L_85:;
    vigil_tc_generic_add(tc, &r[14].v, &r[12].v, &r[9].v, NULL);
L_86:;
    vigil_tc_call_native(tc, (uint64_t *)r, 14, 1, 32, NULL);
L_88:;
    goto L_74;
L_89:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "test.txt", 8, &_s, NULL); vigil_value_init_object(&r[7].v, &_s); }
L_90:;
    vigil_tc_call_native(tc, (uint64_t *)r, 7, 1, 34, NULL);
L_92:;
    r[7].i = (int64_t)0LL;
L_93:;
L_94:;
    tc->ret_count = 1;
    return r[7];
    return (vigil_reg_t){0};
}

