/* Generated by vigil transpile -- do not edit. */
#include "vigil_generated.h"
#include <stdio.h>
#include <stdlib.h>
#include "vigil/transpile_rt.h"
#include "vigil/vigil.h"
#include "vigil/stdlib.h"
#include "vigil/compiler.h"
#include "internal/vigil_internal.h"
#include "plugin_registry.h"

static const char vigil_src_0[] = "import \"fmt\"\nimport \"yaml\"\n\nfn main() -> i32 {\n    // Parse a YAML document (JSON is valid YAML)\n    string doc = \"name: Alice\\nage: 30\\nactive: true\\n\"\n    string name = yaml.get(doc, \"name\")\n    string age_str = yaml.get(doc, \"age\")\n    string active_str = yaml.get(doc, \"active\")\n    fmt.println(f\"Name: {name}\")\n    fmt.println(f\"Age: {age_str}\")\n    fmt.println(f\"Active: {active_str}\")\n    // Parse a YAML list\n    string list_doc = \"items:\\n  - apple\\n  - banana\\n  - cherry\\n\"\n    string item0 = yaml.get(list_doc, \"items[0]\")\n    string item1 = yaml.get(list_doc, \"items[1]\")\n    string item2 = yaml.get(list_doc, \"items[2]\")\n    fmt.println(\"\\nFruit list:\")\n    fmt.println(f\"  [0] = {item0}\")\n    fmt.println(f\"  [1] = {item1}\")\n    fmt.println(f\"  [2] = {item2}\")\n    // Access nested fields\n    string config = \"server:\\n  host: localhost\\n  port: 8080\\ndebug: false\\n\"\n    string host = yaml.get(config, \"server.host\")\n    string port = yaml.get(config, \"server.port\")\n    string debug_val = yaml.get(config, \"debug\")\n    fmt.println(f\"\\nServer config:\")\n    fmt.println(f\"  host: {host}\")\n    fmt.println(f\"  port: {port}\")\n    fmt.println(f\"  debug: {debug_val}\")\n    // yaml.parse converts YAML to a JSON string\n    string as_json = yaml.parse(config)\n    fmt.println(f\"\\nAs JSON: {as_json}\")\n    return 0\n}\n";
static const char vigil_path_0[] = "examples/json_parsing.vigil";

int main(void)
{
    vigil_runtime_t *runtime = NULL;
    vigil_vm_t *vm = NULL;
    vigil_error_t error = {0};
    vigil_source_registry_t registry;
    vigil_diagnostic_list_t diagnostics;
    vigil_object_t *function = NULL;
    vigil_source_id_t sid = 0;
    vigil_tc_t tc = {0};
    if (vigil_runtime_open(&runtime, NULL, &error) != 0) return 1;
    if (vigil_vm_open(&vm, runtime, NULL, &error) != 0)
    { vigil_runtime_close(&runtime); return 1; }
    vigil_vm_set_aot_enabled(vm, 0);
    vigil_source_registry_init(&registry, runtime);
    vigil_diagnostic_list_init(&diagnostics, runtime);
    { vigil_source_id_t _id = 0;
      vigil_source_registry_register_cstr(&registry, vigil_path_0, vigil_src_0, &_id, &error);
      if (0 == 0) sid = _id; }
    { vigil_native_registry_t natives;
      vigil_native_registry_init(&natives);
      vigil_stdlib_register_all(&natives, &error);
      vigil_plugin_register_all(&natives, &error);
      vigil_compile_source_with_natives(&registry, sid, &natives, &function, &diagnostics, &error);
      vigil_native_registry_free(&natives); }
    if (!function) { vigil_diagnostic_list_free(&diagnostics);
      vigil_source_registry_free(&registry); vigil_vm_close(&vm);
      vigil_runtime_close(&runtime); return 1; }
    tc.vm = vm; tc.runtime = runtime;
    tc.function = function;
    { size_t _fi;
      for (_fi = 0; _fi < 1; _fi++) {
        const vigil_object_t *_fn = vigil_function_object_sibling(function, _fi);
        if (!_fn) _fn = function;
        const vigil_chunk_t *_ch = vigil_function_object_chunk(_fn);
        vigil_fn_constants[_fi] = _ch ? (vigil_value_t*)vigil_chunk_constant(_ch, 0) : NULL;
        vigil_fn_constant_counts[_fi] = _ch ? vigil_chunk_constant_count(_ch) : 0;
      }
    }
    tc.constants = vigil_fn_constants[0];
    tc.constant_count = vigil_fn_constant_counts[0];
    vigil_reg_t result = vigil_fn_0(&tc);
    vigil_vm_close(&vm);
    vigil_object_release(&function);
    vigil_diagnostic_list_free(&diagnostics);
    vigil_source_registry_free(&registry);
    vigil_runtime_close(&runtime);
    return (int)result.i;
}
