/* Generated by vigil transpile — do not edit. */
#include "vigil_generated.h"
#include <math.h>
#include <string.h>
#include "vigil/transpile_rt.h"
#include "vigil/value.h"

vigil_value_t *vigil_fn_constants[1];
size_t vigil_fn_constant_counts[1];

vigil_reg_t vigil_fn_0(vigil_tc_t *tc);

vigil_reg_t vigil_fn_0(vigil_tc_t *tc)
{
    vigil_reg_t r[20];
    memset(r, 0, sizeof(r));
    tc->constants = vigil_fn_constants[0];
    tc->constant_count = vigil_fn_constant_counts[0];

L_0:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "name: Alice\nage: 30\nactive: true\n", 33, &_s, NULL); vigil_value_init_object(&r[0].v, &_s); }
L_1:;
    vigil_tc_move_reg(&r[1].v, r[0].v);
L_2:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "name", 4, &_s, NULL); vigil_value_init_object(&r[2].v, &_s); }
L_3:;
    vigil_tc_call_native(tc, (uint64_t *)r, 1, 2, 2, NULL);
L_5:;
    vigil_tc_move_reg(&r[2].v, r[0].v);
L_6:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "age", 3, &_s, NULL); vigil_value_init_object(&r[3].v, &_s); }
L_7:;
    vigil_tc_call_native(tc, (uint64_t *)r, 2, 2, 4, NULL);
L_9:;
    vigil_tc_move_reg(&r[3].v, r[0].v);
L_10:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "active", 6, &_s, NULL); vigil_value_init_object(&r[4].v, &_s); }
L_11:;
    vigil_tc_call_native(tc, (uint64_t *)r, 3, 2, 6, NULL);
L_13:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "Name: ", 6, &_s, NULL); vigil_value_init_object(&r[4].v, &_s); }
L_14:;
L_15:;
    vigil_tc_generic_add(tc, &r[4].v, &r[4].v, &r[1].v, NULL);
L_16:;
    vigil_tc_call_native(tc, (uint64_t *)r, 4, 1, 8, NULL);
L_18:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "Age: ", 5, &_s, NULL); vigil_value_init_object(&r[4].v, &_s); }
L_19:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 126, 5, 0, 0, NULL);
L_20:;
L_21:;
    vigil_tc_generic_add(tc, &r[4].v, &r[4].v, &r[2].v, NULL);
L_22:;
    vigil_tc_call_native(tc, (uint64_t *)r, 4, 1, 10, NULL);
L_24:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "Active: ", 8, &_s, NULL); vigil_value_init_object(&r[4].v, &_s); }
L_25:;
L_26:;
    vigil_tc_generic_add(tc, &r[4].v, &r[4].v, &r[3].v, NULL);
L_27:;
    vigil_tc_call_native(tc, (uint64_t *)r, 4, 1, 12, NULL);
L_29:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "items:\n  - apple\n  - banana\n  - cherry\n", 39, &_s, NULL); vigil_value_init_object(&r[4].v, &_s); }
L_30:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 126, 5, 0, 0, NULL);
L_31:;
    vigil_tc_move_reg(&r[5].v, r[4].v);
L_32:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "items[0]", 8, &_s, NULL); vigil_value_init_object(&r[6].v, &_s); }
L_33:;
    vigil_tc_call_native(tc, (uint64_t *)r, 5, 2, 15, NULL);
L_35:;
    vigil_tc_move_reg(&r[6].v, r[4].v);
L_36:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "items[1]", 8, &_s, NULL); vigil_value_init_object(&r[7].v, &_s); }
L_37:;
    vigil_tc_call_native(tc, (uint64_t *)r, 6, 2, 17, NULL);
L_39:;
    vigil_tc_move_reg(&r[7].v, r[4].v);
L_40:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "items[2]", 8, &_s, NULL); vigil_value_init_object(&r[8].v, &_s); }
L_41:;
    vigil_tc_call_native(tc, (uint64_t *)r, 7, 2, 19, NULL);
L_43:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "\nFruit list:", 12, &_s, NULL); vigil_value_init_object(&r[8].v, &_s); }
L_44:;
    vigil_tc_call_native(tc, (uint64_t *)r, 8, 1, 21, NULL);
L_46:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "  [0] = ", 8, &_s, NULL); vigil_value_init_object(&r[8].v, &_s); }
L_47:;
L_48:;
    vigil_tc_generic_add(tc, &r[8].v, &r[8].v, &r[5].v, NULL);
L_49:;
    vigil_tc_call_native(tc, (uint64_t *)r, 8, 1, 23, NULL);
L_51:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "  [1] = ", 8, &_s, NULL); vigil_value_init_object(&r[8].v, &_s); }
L_52:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 126, 9, 0, 0, NULL);
L_53:;
L_54:;
    vigil_tc_generic_add(tc, &r[8].v, &r[8].v, &r[6].v, NULL);
L_55:;
    vigil_tc_call_native(tc, (uint64_t *)r, 8, 1, 25, NULL);
L_57:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "  [2] = ", 8, &_s, NULL); vigil_value_init_object(&r[8].v, &_s); }
L_58:;
L_59:;
    vigil_tc_generic_add(tc, &r[8].v, &r[8].v, &r[7].v, NULL);
L_60:;
    vigil_tc_call_native(tc, (uint64_t *)r, 8, 1, 27, NULL);
L_62:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "server:\n  host: localhost\n  port: 8080\ndebug: false\n", 52, &_s, NULL); vigil_value_init_object(&r[8].v, &_s); }
L_63:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 126, 9, 0, 0, NULL);
L_64:;
    vigil_tc_move_reg(&r[9].v, r[8].v);
L_65:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "server.host", 11, &_s, NULL); vigil_value_init_object(&r[10].v, &_s); }
L_66:;
    vigil_tc_call_native(tc, (uint64_t *)r, 9, 2, 30, NULL);
L_68:;
    vigil_tc_move_reg(&r[10].v, r[8].v);
L_69:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "server.port", 11, &_s, NULL); vigil_value_init_object(&r[11].v, &_s); }
L_70:;
    vigil_tc_call_native(tc, (uint64_t *)r, 10, 2, 32, NULL);
L_72:;
    vigil_tc_move_reg(&r[11].v, r[8].v);
L_73:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "debug", 5, &_s, NULL); vigil_value_init_object(&r[12].v, &_s); }
L_74:;
    vigil_tc_call_native(tc, (uint64_t *)r, 11, 2, 34, NULL);
L_76:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "\nServer config:", 15, &_s, NULL); vigil_value_init_object(&r[12].v, &_s); }
L_77:;
    vigil_tc_call_native(tc, (uint64_t *)r, 12, 1, 36, NULL);
L_79:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "  host: ", 8, &_s, NULL); vigil_value_init_object(&r[12].v, &_s); }
L_80:;
L_81:;
    vigil_tc_generic_add(tc, &r[12].v, &r[12].v, &r[9].v, NULL);
L_82:;
    vigil_tc_call_native(tc, (uint64_t *)r, 12, 1, 38, NULL);
L_84:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "  port: ", 8, &_s, NULL); vigil_value_init_object(&r[12].v, &_s); }
L_85:;
L_86:;
    vigil_tc_generic_add(tc, &r[12].v, &r[12].v, &r[10].v, NULL);
L_87:;
    vigil_tc_call_native(tc, (uint64_t *)r, 12, 1, 40, NULL);
L_89:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "  debug: ", 9, &_s, NULL); vigil_value_init_object(&r[12].v, &_s); }
L_90:;
L_91:;
    vigil_tc_generic_add(tc, &r[12].v, &r[12].v, &r[11].v, NULL);
L_92:;
    vigil_tc_call_native(tc, (uint64_t *)r, 12, 1, 42, NULL);
L_94:;
    vigil_tc_move_reg(&r[12].v, r[8].v);
L_95:;
    vigil_tc_call_native(tc, (uint64_t *)r, 12, 1, 43, NULL);
L_97:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "\nAs JSON: ", 10, &_s, NULL); vigil_value_init_object(&r[16].v, &_s); }
L_98:;
L_99:;
    vigil_tc_generic_add(tc, &r[18].v, &r[16].v, &r[12].v, NULL);
L_100:;
    vigil_tc_call_native(tc, (uint64_t *)r, 18, 1, 45, NULL);
L_102:;
    r[19].i = (int64_t)0LL;
L_103:;
L_104:;
    tc->ret_count = 1;
    return r[19];
    return (vigil_reg_t){0};
}

