/* Generated by vigil transpile — do not edit. */
#include "vigil_generated.h"
#include <math.h>
#include <string.h>
#include "vigil/transpile_rt.h"
#include "vigil/value.h"

vigil_value_t *vigil_fn_constants[3];
size_t vigil_fn_constant_counts[3];

static vigil_reg_t vigil_fn_0(vigil_tc_t *tc);
static vigil_reg_t vigil_fn_1(vigil_tc_t *tc, vigil_reg_t arg_0, vigil_reg_t arg_1, vigil_reg_t arg_2);
vigil_reg_t vigil_fn_2(vigil_tc_t *tc);

vigil_reg_t vigil_fn_0(vigil_tc_t *tc)
{
    vigil_reg_t r[5];
    memset(r, 0, sizeof(r));
    tc->constants = vigil_fn_constants[0];
    tc->constant_count = vigil_fn_constant_counts[0];

L_0:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 76, 1, 0, 0, NULL);
L_1:;
    vigil_tc_call_native(tc, (uint64_t *)r, 1, 1, 0, NULL);
L_3:;
    r[2].i = !r[1].i;
L_4:;
    if (vigil_tc_is_truthy(r[2].v)) goto L_6;
L_5:;
    goto L_11;
L_6:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 76, 3, 0, 0, NULL);
L_7:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "id,name,age\n", 12, &_s, NULL); vigil_value_init_object(&r[4].v, &_s); }
L_8:;
    vigil_tc_call_native(tc, (uint64_t *)r, 3, 2, 2, NULL);
L_10:;
    goto L_11;
L_11:;
    tc->ret_count = 0;
    return (vigil_reg_t){0};
    return (vigil_reg_t){0};
}

vigil_reg_t vigil_fn_1(vigil_tc_t *tc, vigil_reg_t arg_0, vigil_reg_t arg_1, vigil_reg_t arg_2)
{
    vigil_reg_t r[12];
    memset(r, 0, sizeof(r));
    r[0] = arg_0;
    r[1] = arg_1;
    r[2] = arg_2;
    tc->constants = vigil_fn_constants[1];
    tc->constant_count = vigil_fn_constant_counts[1];

L_0:;
    vigil_tc_move_reg(&r[3].v, r[0].v);
L_1:;
    vigil_tc_move_reg(&r[4].v, r[1].v);
L_2:;
    vigil_tc_move_reg(&r[5].v, r[2].v);
L_3:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 85, 3, 0, 3, NULL);
L_4:;
    vigil_tc_move_reg(&r[4].v, r[3].v);
L_5:;
    vigil_tc_call_native(tc, (uint64_t *)r, 4, 1, 0, NULL);
L_7:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 76, 6, 0, 0, NULL);
L_8:;
    vigil_tc_move_reg(&r[7].v, r[4].v);
L_9:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "\n", 1, &_s, NULL); vigil_value_init_object(&r[8].v, &_s); }
L_10:;
    vigil_tc_generic_add(tc, &r[9].v, &r[7].v, &r[8].v, NULL);
L_11:;
    vigil_tc_move_reg(&r[10].v, r[6].v);
L_12:;
    vigil_tc_move_reg(&r[11].v, r[9].v);
L_13:;
    vigil_tc_call_native(tc, (uint64_t *)r, 10, 2, 2, NULL);
L_15:;
    tc->ret_count = 0;
    return (vigil_reg_t){0};
    return (vigil_reg_t){0};
}

vigil_reg_t vigil_fn_2(vigil_tc_t *tc)
{
    vigil_reg_t r[17];
    memset(r, 0, sizeof(r));
    tc->constants = vigil_fn_constants[2];
    tc->constant_count = vigil_fn_constant_counts[2];

L_0:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "users.csv", 9, &_s, NULL); vigil_value_init_object(&r[0].v, &_s); }
L_1:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 77, 0, 0, 0, NULL);
L_2:;
    { const vigil_value_t *_sc = tc->constants; size_t _sn = tc->constant_count;
    r[0] = vigil_fn_0(tc);
    { uint8_t _ri; for (_ri = 1; _ri < tc->ret_count; _ri++) r[0 + _ri].v = tc->ret_buf[_ri]; }
    tc->constants = _sc; tc->constant_count = _sn; }
L_3:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "1", 1, &_s, NULL); vigil_value_init_object(&r[0].v, &_s); }
L_4:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "Alice", 5, &_s, NULL); vigil_value_init_object(&r[1].v, &_s); }
L_5:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "30", 2, &_s, NULL); vigil_value_init_object(&r[2].v, &_s); }
L_6:;
    { const vigil_value_t *_sc = tc->constants; size_t _sn = tc->constant_count;
    r[0] = vigil_fn_1(tc, r[0], r[1], r[2]);
    { uint8_t _ri; for (_ri = 1; _ri < tc->ret_count; _ri++) r[0 + _ri].v = tc->ret_buf[_ri]; }
    tc->constants = _sc; tc->constant_count = _sn; }
L_7:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "2", 1, &_s, NULL); vigil_value_init_object(&r[0].v, &_s); }
L_8:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 126, 1, 0, 0, NULL);
L_9:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "Bob", 3, &_s, NULL); vigil_value_init_object(&r[1].v, &_s); }
L_10:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 126, 2, 0, 0, NULL);
L_11:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "25", 2, &_s, NULL); vigil_value_init_object(&r[2].v, &_s); }
L_12:;
    { const vigil_value_t *_sc = tc->constants; size_t _sn = tc->constant_count;
    r[0] = vigil_fn_1(tc, r[0], r[1], r[2]);
    { uint8_t _ri; for (_ri = 1; _ri < tc->ret_count; _ri++) r[0 + _ri].v = tc->ret_buf[_ri]; }
    tc->constants = _sc; tc->constant_count = _sn; }
L_13:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "3", 1, &_s, NULL); vigil_value_init_object(&r[0].v, &_s); }
L_14:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "Charlie", 7, &_s, NULL); vigil_value_init_object(&r[1].v, &_s); }
L_15:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "35", 2, &_s, NULL); vigil_value_init_object(&r[2].v, &_s); }
L_16:;
    { const vigil_value_t *_sc = tc->constants; size_t _sn = tc->constant_count;
    r[0] = vigil_fn_1(tc, r[0], r[1], r[2]);
    { uint8_t _ri; for (_ri = 1; _ri < tc->ret_count; _ri++) r[0 + _ri].v = tc->ret_buf[_ri]; }
    tc->constants = _sc; tc->constant_count = _sn; }
L_17:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "Data inserted successfully", 26, &_s, NULL); vigil_value_init_object(&r[0].v, &_s); }
L_18:;
    vigil_tc_call_native(tc, (uint64_t *)r, 0, 1, 11, NULL);
L_20:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 76, 0, 0, 0, NULL);
L_21:;
    vigil_tc_call_native(tc, (uint64_t *)r, 0, 1, 12, NULL);
L_23:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 126, 1, 0, 0, NULL);
L_24:;
    vigil_tc_move_reg(&r[1].v, r[0].v);
L_25:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 126, 2, 0, 0, NULL);
L_26:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "\n", 1, &_s, NULL); vigil_value_init_object(&r[2].v, &_s); }
L_27:;
    vigil_tc_string_op(tc, (uint64_t *)r, 1, 2, 71, NULL);
L_28:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "\nUsers in database:", 19, &_s, NULL); vigil_value_init_object(&r[2].v, &_s); }
L_29:;
    vigil_tc_call_native(tc, (uint64_t *)r, 2, 1, 15, NULL);
L_31:;
    r[2].i = (int64_t)1LL;
L_32:;
    vigil_tc_move_reg(&r[3].v, r[2].v);
L_33:;
    vigil_tc_move_reg(&r[4].v, r[1].v);
L_34:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 89, 4, 4, 0, NULL);
L_35:;
    if ((int32_t)r[3].i < (int32_t)r[4].i) goto L_37;
L_36:;
    goto L_83;
L_37:;
    goto L_40;
L_38:;
    r[2].i = (int64_t)((int32_t)r[2].i + (int32_t)1);
L_39:;
    goto L_32;
L_40:;
    vigil_tc_move_reg(&r[3].v, r[1].v);
L_41:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 126, 4, 0, 0, NULL);
L_42:;
    vigil_tc_move_reg(&r[4].v, r[2].v);
L_43:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 87, 3, 3, 4, NULL);
L_44:;
    vigil_tc_string_op(tc, (uint64_t *)r, 3, 3, 67, NULL);
L_45:;
    vigil_tc_move_reg(&r[4].v, r[3].v);
L_46:;
    vigil_tc_string_op(tc, (uint64_t *)r, 4, 4, 138, NULL);
L_47:;
    if (vigil_tc_is_truthy(r[4].v)) goto L_49;
L_48:;
    goto L_50;
L_49:;
    goto L_38;
L_50:;
    vigil_tc_move_reg(&r[4].v, r[3].v);
L_51:;
    vigil_tc_call_native(tc, (uint64_t *)r, 4, 1, 18, NULL);
L_53:;
    vigil_tc_move_reg(&r[5].v, r[4].v);
L_54:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 89, 5, 5, 0, NULL);
L_55:;
    r[6].i = (int64_t)3LL;
L_56:;
    if ((int32_t)r[5].i >= (int32_t)r[6].i) goto L_58;
L_57:;
    goto L_82;
L_58:;
    vigil_tc_move_reg(&r[5].v, r[4].v);
L_59:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 126, 6, 0, 0, NULL);
L_60:;
    r[6].i = (int64_t)0LL;
L_61:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 87, 5, 5, 6, NULL);
L_62:;
    vigil_tc_move_reg(&r[6].v, r[4].v);
L_63:;
    r[7].i = (int64_t)1LL;
L_64:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 87, 6, 6, 7, NULL);
L_65:;
    vigil_tc_move_reg(&r[7].v, r[4].v);
L_66:;
    r[8].i = (int64_t)2LL;
L_67:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 87, 7, 7, 8, NULL);
L_68:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "  ID: ", 6, &_s, NULL); vigil_value_init_object(&r[8].v, &_s); }
L_69:;
L_70:;
    vigil_tc_generic_add(tc, &r[8].v, &r[8].v, &r[5].v, NULL);
L_71:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, ", Name: ", 8, &_s, NULL); vigil_value_init_object(&r[10].v, &_s); }
L_72:;
    vigil_tc_generic_add(tc, &r[8].v, &r[8].v, &r[10].v, NULL);
L_73:;
L_74:;
    vigil_tc_generic_add(tc, &r[8].v, &r[8].v, &r[6].v, NULL);
L_75:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, ", Age: ", 7, &_s, NULL); vigil_value_init_object(&r[12].v, &_s); }
L_76:;
    vigil_tc_generic_add(tc, &r[8].v, &r[8].v, &r[12].v, NULL);
L_77:;
L_78:;
    vigil_tc_generic_add(tc, &r[8].v, &r[8].v, &r[7].v, NULL);
L_79:;
    vigil_tc_call_native(tc, (uint64_t *)r, 8, 1, 26, NULL);
L_81:;
    goto L_82;
L_82:;
    goto L_38;
L_83:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "\nUsers older than 28:", 21, &_s, NULL); vigil_value_init_object(&r[2].v, &_s); }
L_84:;
    vigil_tc_call_native(tc, (uint64_t *)r, 2, 1, 28, NULL);
L_86:;
    r[2].i = (int64_t)1LL;
L_87:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 126, 3, 0, 0, NULL);
L_88:;
    vigil_tc_move_reg(&r[3].v, r[2].v);
L_89:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 126, 4, 0, 0, NULL);
L_90:;
    vigil_tc_move_reg(&r[4].v, r[1].v);
L_91:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 89, 4, 4, 0, NULL);
L_92:;
    if ((int32_t)r[3].i < (int32_t)r[4].i) goto L_94;
L_93:;
    goto L_142;
L_94:;
    goto L_97;
L_95:;
    r[2].i = (int64_t)((int32_t)r[2].i + (int32_t)1);
L_96:;
    goto L_87;
L_97:;
    vigil_tc_move_reg(&r[3].v, r[1].v);
L_98:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 126, 4, 0, 0, NULL);
L_99:;
    vigil_tc_move_reg(&r[4].v, r[2].v);
L_100:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 87, 3, 3, 4, NULL);
L_101:;
    vigil_tc_string_op(tc, (uint64_t *)r, 3, 3, 67, NULL);
L_102:;
    vigil_tc_move_reg(&r[4].v, r[3].v);
L_103:;
    vigil_tc_string_op(tc, (uint64_t *)r, 4, 4, 138, NULL);
L_104:;
    if (vigil_tc_is_truthy(r[4].v)) goto L_106;
L_105:;
    goto L_107;
L_106:;
    goto L_95;
L_107:;
    vigil_tc_move_reg(&r[4].v, r[3].v);
L_108:;
    vigil_tc_call_native(tc, (uint64_t *)r, 4, 1, 31, NULL);
L_110:;
    vigil_tc_move_reg(&r[5].v, r[4].v);
L_111:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 89, 5, 5, 0, NULL);
L_112:;
    r[6].i = (int64_t)3LL;
L_113:;
    r[5].i = (r[6].i <= r[5].i);
L_114:;
    if (vigil_tc_is_truthy(r[5].v)) goto L_116;
L_115:;
    goto L_141;
L_116:;
    vigil_tc_move_reg(&r[5].v, r[4].v);
L_117:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 126, 6, 0, 0, NULL);
L_118:;
    r[6].i = (int64_t)1LL;
L_119:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 87, 5, 5, 6, NULL);
L_120:;
    vigil_tc_move_reg(&r[6].v, r[4].v);
L_121:;
    r[7].i = (int64_t)2LL;
L_122:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 87, 6, 6, 7, NULL);
L_123:;
    vigil_tc_move_reg(&r[7].v, r[6].v);
L_124:;
    vigil_tc_parse_i32(tc, &r[7].v, &r[7].v, NULL);
L_125:;
    vigil_tc_move_reg(&r[9].v, r[8].v);
L_126:;
    r[10].v = vigil_value_copy(&tc->constants[35]);
L_127:;
    r[11].i = vigil_tc_values_equal((uint64_t *)r, 9, 10);
L_128:;
    if (vigil_tc_is_truthy(r[11].v)) goto L_130;
L_129:;
    goto L_132;
L_130:;
    vigil_tc_move_reg(&r[12].v, r[7].v);
L_131:;
    r[13].i = (int64_t)28LL;
L_132:;
    if ((int32_t)r[12].i > (int32_t)r[13].i) goto L_134;
L_133:;
    goto L_140;
L_134:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "  - ", 4, &_s, NULL); vigil_value_init_object(&r[14].v, &_s); }
L_135:;
L_136:;
    vigil_tc_generic_add(tc, &r[16].v, &r[14].v, &r[5].v, NULL);
L_137:;
    vigil_tc_call_native(tc, (uint64_t *)r, 16, 1, 38, NULL);
L_139:;
    goto L_140;
L_140:;
    goto L_141;
L_141:;
    goto L_95;
L_142:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 76, 2, 0, 0, NULL);
L_143:;
    vigil_tc_call_native(tc, (uint64_t *)r, 2, 1, 39, NULL);
L_145:;
    r[2].i = (int64_t)0LL;
L_146:;
L_147:;
    tc->ret_count = 1;
    return r[2];
    return (vigil_reg_t){0};
}

