/* Generated by vigil transpile — do not edit. */
#include "vigil_generated.h"
#include <math.h>
#include <string.h>
#include "vigil/transpile_rt.h"
#include "vigil/value.h"

vigil_value_t *vigil_fn_constants[1];
size_t vigil_fn_constant_counts[1];

vigil_reg_t vigil_fn_0(vigil_tc_t *tc);

vigil_reg_t vigil_fn_0(vigil_tc_t *tc)
{
    vigil_reg_t r[3];
    memset(r, 0, sizeof(r));
    tc->constants = vigil_fn_constants[0];
    tc->constant_count = vigil_fn_constant_counts[0];

L_0:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "Hello, World!", 13, &_s, NULL); vigil_value_init_object(&r[1].v, &_s); }
L_1:;
    vigil_tc_call_native(tc, (uint64_t *)r, 1, 1, 1, NULL);
L_3:;
    r[2].i = (int64_t)0LL;
L_4:;
L_5:;
    tc->ret_count = 1;
    return r[2];
    return (vigil_reg_t){0};
}

