/* Generated by vigil transpile -- do not edit. */
#include "vigil_generated.h"
#include <stdio.h>
#include <stdlib.h>
#include "vigil/transpile_rt.h"
#include "vigil/vigil.h"
#include "vigil/stdlib.h"
#include "vigil/compiler.h"
#include "internal/vigil_internal.h"
#include "plugin_registry.h"

static const char vigil_src_0[] = "import \"fmt\"\nimport \"regex\"\n\nfn main() -> i32 {\n    string text = \"Contact us at support@example.com or sales@example.com\"\n    // Match pattern — returns bool directly\n    bool matches = regex.match(\"example\\\\.com\", text)\n    fmt.println(f\"Contains 'example.com': {matches}\")\n    // Find first match — returns (string, bool)\n    string email, bool found = regex.find(\"[a-z]+@[a-z]+\\\\.[a-z]+\", text)\n    if found {\n        fmt.println(f\"First email found: {email}\")\n    }\n\n    // Find all matches — returns array<string> directly\n    array<string> emails = regex.find_all(\"[a-z]+@[a-z]+\\\\.[a-z]+\", text)\n    fmt.println(f\"All emails found ({emails.len()}):\")\n    for addr in emails {\n        fmt.println(f\"  - {addr}\")\n    }\n\n    // Replace pattern — returns string directly; args are (pattern, input, replacement)\n    string replaced = regex.replace(\"@example\\\\.com\", text, \"@newdomain.com\")\n    fmt.println(f\"After replacement: {replaced}\")\n    // Split by pattern — returns array<string>; args are (pattern, input)\n    string csv = \"apple,banana,cherry,date\"\n    array<string> fruits = regex.split(\",\", csv)\n    fmt.println(f\"\\nSplit CSV ({fruits.len()} items):\")\n    for fruit in fruits {\n        fmt.println(f\"  - {fruit}\")\n    }\n\n    // Validate phone number\n    string phone = \"555-123-4567\"\n    bool valid = regex.match(\"^\\\\d{3}-\\\\d{3}-\\\\d{4}$\", phone)\n    fmt.println(f\"\\nPhone '{phone}' is valid: {valid}\")\n    return 0\n}\n";
static const char vigil_path_0[] = "examples/regex_patterns.vigil";

int main(void)
{
    vigil_runtime_t *runtime = NULL;
    vigil_vm_t *vm = NULL;
    vigil_error_t error = {0};
    vigil_source_registry_t registry;
    vigil_diagnostic_list_t diagnostics;
    vigil_object_t *function = NULL;
    vigil_source_id_t sid = 0;
    vigil_tc_t tc = {0};
    if (vigil_runtime_open(&runtime, NULL, &error) != 0) return 1;
    if (vigil_vm_open(&vm, runtime, NULL, &error) != 0)
    { vigil_runtime_close(&runtime); return 1; }
    vigil_vm_set_aot_enabled(vm, 0);
    vigil_source_registry_init(&registry, runtime);
    vigil_diagnostic_list_init(&diagnostics, runtime);
    { vigil_source_id_t _id = 0;
      vigil_source_registry_register_cstr(&registry, vigil_path_0, vigil_src_0, &_id, &error);
      if (0 == 0) sid = _id; }
    { vigil_native_registry_t natives;
      vigil_native_registry_init(&natives);
      vigil_stdlib_register_all(&natives, &error);
      vigil_plugin_register_all(&natives, &error);
      vigil_compile_source_with_natives(&registry, sid, &natives, &function, &diagnostics, &error);
      vigil_native_registry_free(&natives); }
    if (!function) { vigil_diagnostic_list_free(&diagnostics);
      vigil_source_registry_free(&registry); vigil_vm_close(&vm);
      vigil_runtime_close(&runtime); return 1; }
    tc.vm = vm; tc.runtime = runtime;
    tc.function = function;
    { size_t _fi;
      for (_fi = 0; _fi < 1; _fi++) {
        const vigil_object_t *_fn = vigil_function_object_sibling(function, _fi);
        if (!_fn) _fn = function;
        const vigil_chunk_t *_ch = vigil_function_object_chunk(_fn);
        vigil_fn_constants[_fi] = _ch ? (vigil_value_t*)vigil_chunk_constant(_ch, 0) : NULL;
        vigil_fn_constant_counts[_fi] = _ch ? vigil_chunk_constant_count(_ch) : 0;
      }
    }
    tc.constants = vigil_fn_constants[0];
    tc.constant_count = vigil_fn_constant_counts[0];
    vigil_reg_t result = vigil_fn_0(&tc);
    vigil_vm_close(&vm);
    vigil_object_release(&function);
    vigil_diagnostic_list_free(&diagnostics);
    vigil_source_registry_free(&registry);
    vigil_runtime_close(&runtime);
    return (int)result.i;
}
