/* Generated by vigil transpile — do not edit. */
#include "vigil_generated.h"
#include <math.h>
#include <string.h>
#include "vigil/transpile_rt.h"
#include "vigil/value.h"

vigil_value_t *vigil_fn_constants[1];
size_t vigil_fn_constant_counts[1];

vigil_reg_t vigil_fn_0(vigil_tc_t *tc);

vigil_reg_t vigil_fn_0(vigil_tc_t *tc)
{
    vigil_reg_t r[16];
    memset(r, 0, sizeof(r));
    tc->constants = vigil_fn_constants[0];
    tc->constant_count = vigil_fn_constant_counts[0];

L_0:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "Contact us at support@example.com or sales@example.com", 54, &_s, NULL); vigil_value_init_object(&r[0].v, &_s); }
L_1:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "example\\.com", 12, &_s, NULL); vigil_value_init_object(&r[1].v, &_s); }
L_2:;
    vigil_tc_move_reg(&r[2].v, r[0].v);
L_3:;
    vigil_tc_call_native(tc, (uint64_t *)r, 1, 2, 2, NULL);
L_5:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "Contains 'example.com': ", 24, &_s, NULL); vigil_value_init_object(&r[2].v, &_s); }
L_6:;
    vigil_tc_move_reg(&r[3].v, r[1].v);
L_7:;
    vigil_tc_to_string(tc, &r[3].v, &r[3].v, NULL);
L_8:;
    vigil_tc_generic_add(tc, &r[2].v, &r[2].v, &r[3].v, NULL);
L_9:;
    vigil_tc_call_native(tc, (uint64_t *)r, 2, 1, 4, NULL);
L_11:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "[a-z]+@[a-z]+\\.[a-z]+", 21, &_s, NULL); vigil_value_init_object(&r[2].v, &_s); }
L_12:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 126, 3, 0, 0, NULL);
L_13:;
    vigil_tc_move_reg(&r[3].v, r[0].v);
L_14:;
    vigil_tc_call_native(tc, (uint64_t *)r, 2, 2, 6, NULL);
L_16:;
L_17:;
    if (vigil_tc_is_truthy(r[3].v)) goto L_19;
L_18:;
    goto L_25;
L_19:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "First email found: ", 19, &_s, NULL); vigil_value_init_object(&r[4].v, &_s); }
L_20:;
L_21:;
    vigil_tc_generic_add(tc, &r[4].v, &r[4].v, &r[2].v, NULL);
L_22:;
    vigil_tc_call_native(tc, (uint64_t *)r, 4, 1, 8, NULL);
L_24:;
    goto L_25;
L_25:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "[a-z]+@[a-z]+\\.[a-z]+", 21, &_s, NULL); vigil_value_init_object(&r[4].v, &_s); }
L_26:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 126, 5, 0, 0, NULL);
L_27:;
    vigil_tc_move_reg(&r[5].v, r[0].v);
L_28:;
    vigil_tc_call_native(tc, (uint64_t *)r, 4, 2, 10, NULL);
L_30:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "All emails found (", 18, &_s, NULL); vigil_value_init_object(&r[5].v, &_s); }
L_31:;
    vigil_tc_move_reg(&r[6].v, r[4].v);
L_32:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 89, 6, 6, 0, NULL);
L_33:;
    vigil_tc_to_string(tc, &r[6].v, &r[6].v, NULL);
L_34:;
    vigil_tc_generic_add(tc, &r[5].v, &r[5].v, &r[6].v, NULL);
L_35:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 126, 6, 0, 0, NULL);
L_36:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "):", 2, &_s, NULL); vigil_value_init_object(&r[6].v, &_s); }
L_37:;
    vigil_tc_generic_add(tc, &r[5].v, &r[5].v, &r[6].v, NULL);
L_38:;
    vigil_tc_call_native(tc, (uint64_t *)r, 5, 1, 13, NULL);
L_40:;
    vigil_tc_move_reg(&r[5].v, r[4].v);
L_41:;
    r[6].i = (int64_t)0LL;
L_42:;
    vigil_tc_move_reg(&r[7].v, r[6].v);
L_43:;
    vigil_tc_move_reg(&r[8].v, r[5].v);
L_44:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 89, 8, 8, 0, NULL);
L_45:;
    r[7].i = (r[7].i < r[8].i);
L_46:;
    if (vigil_tc_is_truthy(r[7].v)) goto L_48;
L_47:;
    goto L_65;
L_48:;
    goto L_55;
L_49:;
    vigil_tc_move_reg(&r[7].v, r[6].v);
L_50:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 126, 8, 0, 0, NULL);
L_51:;
    r[8].i = (int64_t)1LL;
L_52:;
    vigil_tc_generic_add(tc, &r[7].v, &r[7].v, &r[8].v, NULL);
L_53:;
    vigil_tc_move_reg(&r[6].v, r[7].v);
L_54:;
    goto L_42;
L_55:;
    vigil_tc_move_reg(&r[7].v, r[5].v);
L_56:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 126, 8, 0, 0, NULL);
L_57:;
    vigil_tc_move_reg(&r[8].v, r[6].v);
L_58:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 87, 7, 7, 8, NULL);
L_59:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "  - ", 4, &_s, NULL); vigil_value_init_object(&r[8].v, &_s); }
L_60:;
L_61:;
    vigil_tc_generic_add(tc, &r[8].v, &r[8].v, &r[7].v, NULL);
L_62:;
    vigil_tc_call_native(tc, (uint64_t *)r, 8, 1, 17, NULL);
L_64:;
    goto L_49;
L_65:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "@example\\.com", 13, &_s, NULL); vigil_value_init_object(&r[5].v, &_s); }
L_66:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 126, 6, 0, 0, NULL);
L_67:;
    vigil_tc_move_reg(&r[6].v, r[0].v);
L_68:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 126, 7, 0, 0, NULL);
L_69:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "@newdomain.com", 14, &_s, NULL); vigil_value_init_object(&r[7].v, &_s); }
L_70:;
    vigil_tc_call_native(tc, (uint64_t *)r, 5, 3, 20, NULL);
L_72:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "After replacement: ", 19, &_s, NULL); vigil_value_init_object(&r[6].v, &_s); }
L_73:;
L_74:;
    vigil_tc_generic_add(tc, &r[6].v, &r[6].v, &r[5].v, NULL);
L_75:;
    vigil_tc_call_native(tc, (uint64_t *)r, 6, 1, 22, NULL);
L_77:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "apple,banana,cherry,date", 24, &_s, NULL); vigil_value_init_object(&r[6].v, &_s); }
L_78:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 126, 7, 0, 0, NULL);
L_79:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, ",", 1, &_s, NULL); vigil_value_init_object(&r[7].v, &_s); }
L_80:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 126, 8, 0, 0, NULL);
L_81:;
    vigil_tc_move_reg(&r[8].v, r[6].v);
L_82:;
    vigil_tc_call_native(tc, (uint64_t *)r, 7, 2, 25, NULL);
L_84:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "\nSplit CSV (", 12, &_s, NULL); vigil_value_init_object(&r[8].v, &_s); }
L_85:;
    vigil_tc_move_reg(&r[9].v, r[7].v);
L_86:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 89, 9, 9, 0, NULL);
L_87:;
    vigil_tc_to_string(tc, &r[9].v, &r[9].v, NULL);
L_88:;
    vigil_tc_generic_add(tc, &r[8].v, &r[8].v, &r[9].v, NULL);
L_89:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 126, 9, 0, 0, NULL);
L_90:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, " items):", 8, &_s, NULL); vigil_value_init_object(&r[9].v, &_s); }
L_91:;
    vigil_tc_generic_add(tc, &r[8].v, &r[8].v, &r[9].v, NULL);
L_92:;
    vigil_tc_call_native(tc, (uint64_t *)r, 8, 1, 28, NULL);
L_94:;
    vigil_tc_move_reg(&r[8].v, r[7].v);
L_95:;
    r[9].i = (int64_t)0LL;
L_96:;
    vigil_tc_move_reg(&r[10].v, r[9].v);
L_97:;
    vigil_tc_move_reg(&r[11].v, r[8].v);
L_98:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 89, 11, 11, 0, NULL);
L_99:;
    r[10].i = (r[10].i < r[11].i);
L_100:;
    if (vigil_tc_is_truthy(r[10].v)) goto L_102;
L_101:;
    goto L_118;
L_102:;
    goto L_108;
L_103:;
    vigil_tc_move_reg(&r[10].v, r[9].v);
L_104:;
    r[12].i = (int64_t)1LL;
L_105:;
    vigil_tc_generic_add(tc, &r[10].v, &r[10].v, &r[12].v, NULL);
L_106:;
    vigil_tc_move_reg(&r[9].v, r[10].v);
L_107:;
    goto L_96;
L_108:;
    vigil_tc_move_reg(&r[10].v, r[8].v);
L_109:;
    vigil_tc_move_reg(&r[12].v, r[9].v);
L_110:;
    vigil_tc_move_reg(&r[11].v, r[10].v);
L_111:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 87, 10, 11, 12, NULL);
L_112:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "  - ", 4, &_s, NULL); vigil_value_init_object(&r[13].v, &_s); }
L_113:;
L_114:;
    vigil_tc_generic_add(tc, &r[15].v, &r[13].v, &r[10].v, NULL);
L_115:;
    vigil_tc_call_native(tc, (uint64_t *)r, 15, 1, 32, NULL);
L_117:;
    goto L_103;
L_118:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "555-123-4567", 12, &_s, NULL); vigil_value_init_object(&r[8].v, &_s); }
L_119:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 126, 9, 0, 0, NULL);
L_120:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "^\\d{3}-\\d{3}-\\d{4}$", 19, &_s, NULL); vigil_value_init_object(&r[9].v, &_s); }
L_121:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 126, 10, 0, 0, NULL);
L_122:;
    vigil_tc_move_reg(&r[10].v, r[8].v);
L_123:;
    vigil_tc_call_native(tc, (uint64_t *)r, 9, 2, 35, NULL);
L_125:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "\nPhone '", 8, &_s, NULL); vigil_value_init_object(&r[10].v, &_s); }
L_126:;
L_127:;
    vigil_tc_generic_add(tc, &r[10].v, &r[10].v, &r[8].v, NULL);
L_128:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "' is valid: ", 12, &_s, NULL); vigil_value_init_object(&r[13].v, &_s); }
L_129:;
    vigil_tc_generic_add(tc, &r[10].v, &r[10].v, &r[13].v, NULL);
L_130:;
    vigil_tc_move_reg(&r[14].v, r[9].v);
L_131:;
    vigil_tc_to_string(tc, &r[14].v, &r[14].v, NULL);
L_132:;
    vigil_tc_generic_add(tc, &r[10].v, &r[10].v, &r[14].v, NULL);
L_133:;
    vigil_tc_call_native(tc, (uint64_t *)r, 10, 1, 38, NULL);
L_135:;
    r[10].i = (int64_t)0LL;
L_136:;
L_137:;
    tc->ret_count = 1;
    return r[10];
    return (vigil_reg_t){0};
}

