/* Generated by vigil transpile — do not edit. */
#include "vigil_generated.h"
#include <math.h>
#include <string.h>
#include "vigil/transpile_rt.h"
#include "vigil/value.h"

vigil_value_t *vigil_fn_constants[10];
size_t vigil_fn_constant_counts[10];

static vigil_reg_t vigil_fn_0(vigil_tc_t *tc, vigil_reg_t arg_0, vigil_reg_t arg_1, vigil_reg_t arg_2);
static vigil_reg_t vigil_fn_1(vigil_tc_t *tc, vigil_reg_t arg_0);
static vigil_reg_t vigil_fn_2(vigil_tc_t *tc, vigil_reg_t arg_0);
static vigil_reg_t vigil_fn_3(vigil_tc_t *tc, vigil_reg_t arg_0, vigil_reg_t arg_1);
static vigil_reg_t vigil_fn_4(vigil_tc_t *tc, vigil_reg_t arg_0, vigil_reg_t arg_1, vigil_reg_t arg_2);
static vigil_reg_t vigil_fn_5(vigil_tc_t *tc, vigil_reg_t arg_0);
static vigil_reg_t vigil_fn_6(vigil_tc_t *tc, vigil_reg_t arg_0);
static vigil_reg_t vigil_fn_7(vigil_tc_t *tc, vigil_reg_t arg_0, vigil_reg_t arg_1);
static vigil_reg_t vigil_fn_8(vigil_tc_t *tc, vigil_reg_t arg_0, vigil_reg_t arg_1);
vigil_reg_t vigil_fn_9(vigil_tc_t *tc);

vigil_reg_t vigil_fn_0(vigil_tc_t *tc, vigil_reg_t arg_0, vigil_reg_t arg_1, vigil_reg_t arg_2)
{
    vigil_reg_t r[7];
    memset(r, 0, sizeof(r));
    r[0] = arg_0;
    r[1] = arg_1;
    r[2] = arg_2;
    tc->constants = vigil_fn_constants[0];
    tc->constant_count = vigil_fn_constant_counts[0];

L_0:;
    vigil_tc_move_reg(&r[3].v, r[0].v);
L_1:;
    vigil_tc_move_reg(&r[4].v, r[1].v);
L_2:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 84, 3, 0, 4, NULL);
L_3:;
    vigil_tc_move_reg(&r[5].v, r[0].v);
L_4:;
    vigil_tc_move_reg(&r[6].v, r[2].v);
L_5:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 84, 5, 1, 6, NULL);
L_6:;
    tc->ret_count = 0;
    return (vigil_reg_t){0};
    return (vigil_reg_t){0};
}

vigil_reg_t vigil_fn_1(vigil_tc_t *tc, vigil_reg_t arg_0)
{
    vigil_reg_t r[10];
    memset(r, 0, sizeof(r));
    r[0] = arg_0;
    tc->constants = vigil_fn_constants[1];
    tc->constant_count = vigil_fn_constant_counts[1];

L_0:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "Hello, I'm ", 11, &_s, NULL); vigil_value_init_object(&r[1].v, &_s); }
L_1:;
    vigil_tc_move_reg(&r[2].v, r[0].v);
L_2:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 83, 2, 2, 0, NULL);
L_3:;
    vigil_tc_generic_add(tc, &r[3].v, &r[1].v, &r[2].v, NULL);
L_4:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, " and I'm ", 9, &_s, NULL); vigil_value_init_object(&r[4].v, &_s); }
L_5:;
    vigil_tc_generic_add(tc, &r[5].v, &r[3].v, &r[4].v, NULL);
L_6:;
    vigil_tc_move_reg(&r[6].v, r[0].v);
L_7:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 83, 6, 6, 1, NULL);
L_8:;
    vigil_tc_to_string(tc, &r[6].v, &r[6].v, NULL);
L_9:;
    vigil_tc_generic_add(tc, &r[7].v, &r[5].v, &r[6].v, NULL);
L_10:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, " years old", 10, &_s, NULL); vigil_value_init_object(&r[8].v, &_s); }
L_11:;
    vigil_tc_generic_add(tc, &r[9].v, &r[7].v, &r[8].v, NULL);
L_12:;
    vigil_tc_call_native(tc, (uint64_t *)r, 9, 1, 3, NULL);
L_14:;
    tc->ret_count = 0;
    return (vigil_reg_t){0};
    return (vigil_reg_t){0};
}

vigil_reg_t vigil_fn_2(vigil_tc_t *tc, vigil_reg_t arg_0)
{
    vigil_reg_t r[12];
    memset(r, 0, sizeof(r));
    r[0] = arg_0;
    tc->constants = vigil_fn_constants[2];
    tc->constant_count = vigil_fn_constant_counts[2];

L_0:;
    vigil_tc_move_reg(&r[1].v, r[0].v);
L_1:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 125, 2, 1, 0, NULL);
L_2:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 83, 2, 2, 1, NULL);
L_3:;
    r[4].i = (int64_t)((int32_t)r[2].i + (int32_t)1);
L_4:;
    vigil_tc_move_reg(&r[3].v, r[1].v);
L_5:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 84, 3, 1, 4, NULL);
L_6:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "Happy birthday! ", 16, &_s, NULL); vigil_value_init_object(&r[5].v, &_s); }
L_7:;
    vigil_tc_move_reg(&r[6].v, r[0].v);
L_8:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 83, 6, 6, 0, NULL);
L_9:;
    vigil_tc_generic_add(tc, &r[7].v, &r[5].v, &r[6].v, NULL);
L_10:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, " is now ", 8, &_s, NULL); vigil_value_init_object(&r[8].v, &_s); }
L_11:;
    vigil_tc_generic_add(tc, &r[9].v, &r[7].v, &r[8].v, NULL);
L_12:;
    vigil_tc_move_reg(&r[10].v, r[0].v);
L_13:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 83, 10, 10, 1, NULL);
L_14:;
    vigil_tc_to_string(tc, &r[10].v, &r[10].v, NULL);
L_15:;
    vigil_tc_generic_add(tc, &r[11].v, &r[9].v, &r[10].v, NULL);
L_16:;
    vigil_tc_call_native(tc, (uint64_t *)r, 11, 1, 3, NULL);
L_18:;
    tc->ret_count = 0;
    return (vigil_reg_t){0};
    return (vigil_reg_t){0};
}

vigil_reg_t vigil_fn_3(vigil_tc_t *tc, vigil_reg_t arg_0, vigil_reg_t arg_1)
{
    vigil_reg_t r[8];
    memset(r, 0, sizeof(r));
    r[0] = arg_0;
    r[1] = arg_1;
    tc->constants = vigil_fn_constants[3];
    tc->constant_count = vigil_fn_constant_counts[3];

L_0:;
    r[2].i = 0;
L_1:;
    r[3].i = 0;
L_2:;
    { uint16_t _ci = 5; uint8_t _fb = 2, _fc = 2;
      vigil_tc_new_instance(tc, (uint64_t *)r, 4, _ci, _fb, _fc, NULL); }
L_4:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 125, 5, 4, 0, NULL);
L_5:;
    vigil_tc_move_reg(&r[6].v, r[0].v);
L_6:;
    vigil_tc_move_reg(&r[7].v, r[1].v);
L_7:;
    { const vigil_value_t *_sc = tc->constants; size_t _sn = tc->constant_count;
    r[5] = vigil_fn_0(tc, r[5], r[6], r[7]);
    { uint8_t _ri; for (_ri = 1; _ri < tc->ret_count; _ri++) r[5 + _ri].v = tc->ret_buf[_ri]; }
    tc->constants = _sc; tc->constant_count = _sn; }
L_8:;
L_9:;
    tc->ret_count = 1;
    return r[4];
    return (vigil_reg_t){0};
}

vigil_reg_t vigil_fn_4(vigil_tc_t *tc, vigil_reg_t arg_0, vigil_reg_t arg_1, vigil_reg_t arg_2)
{
    vigil_reg_t r[7];
    memset(r, 0, sizeof(r));
    r[0] = arg_0;
    r[1] = arg_1;
    r[2] = arg_2;
    tc->constants = vigil_fn_constants[4];
    tc->constant_count = vigil_fn_constant_counts[4];

L_0:;
    vigil_tc_move_reg(&r[3].v, r[0].v);
L_1:;
    vigil_tc_move_reg(&r[4].v, r[1].v);
L_2:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 84, 3, 0, 4, NULL);
L_3:;
    vigil_tc_move_reg(&r[5].v, r[0].v);
L_4:;
    vigil_tc_move_reg(&r[6].v, r[2].v);
L_5:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 84, 5, 1, 6, NULL);
L_6:;
    tc->ret_count = 0;
    return (vigil_reg_t){0};
    return (vigil_reg_t){0};
}

vigil_reg_t vigil_fn_5(vigil_tc_t *tc, vigil_reg_t arg_0)
{
    vigil_reg_t r[4];
    memset(r, 0, sizeof(r));
    r[0] = arg_0;
    tc->constants = vigil_fn_constants[5];
    tc->constant_count = vigil_fn_constant_counts[5];

L_0:;
    vigil_tc_move_reg(&r[1].v, r[0].v);
L_1:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 83, 1, 1, 0, NULL);
L_2:;
    vigil_tc_move_reg(&r[2].v, r[0].v);
L_3:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 83, 2, 2, 1, NULL);
L_4:;
    r[3].f = r[1].f * r[2].f;
L_5:;
L_6:;
    tc->ret_count = 1;
    return r[3];
    return (vigil_reg_t){0};
}

vigil_reg_t vigil_fn_6(vigil_tc_t *tc, vigil_reg_t arg_0)
{
    vigil_reg_t r[6];
    memset(r, 0, sizeof(r));
    r[0] = arg_0;
    tc->constants = vigil_fn_constants[6];
    tc->constant_count = vigil_fn_constant_counts[6];

L_0:;
    r[1].f = 2;
L_1:;
    vigil_tc_move_reg(&r[2].v, r[0].v);
L_2:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 83, 2, 2, 0, NULL);
L_3:;
    vigil_tc_move_reg(&r[3].v, r[0].v);
L_4:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 83, 3, 3, 1, NULL);
L_5:;
    r[4].f = r[2].f + r[3].f;
L_6:;
    r[5].f = r[1].f * r[4].f;
L_7:;
L_8:;
    tc->ret_count = 1;
    return r[5];
    return (vigil_reg_t){0};
}

vigil_reg_t vigil_fn_7(vigil_tc_t *tc, vigil_reg_t arg_0, vigil_reg_t arg_1)
{
    vigil_reg_t r[10];
    memset(r, 0, sizeof(r));
    r[0] = arg_0;
    r[1] = arg_1;
    tc->constants = vigil_fn_constants[7];
    tc->constant_count = vigil_fn_constant_counts[7];

L_0:;
    vigil_tc_move_reg(&r[2].v, r[0].v);
L_1:;
    vigil_tc_move_reg(&r[3].v, r[0].v);
L_2:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 83, 3, 3, 0, NULL);
L_3:;
L_4:;
    r[5].f = r[3].f * r[1].f;
L_5:;
    vigil_tc_move_reg(&r[4].v, r[2].v);
L_6:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 84, 4, 0, 5, NULL);
L_7:;
    vigil_tc_move_reg(&r[6].v, r[0].v);
L_8:;
    vigil_tc_move_reg(&r[7].v, r[0].v);
L_9:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 83, 7, 7, 1, NULL);
L_10:;
L_11:;
    r[9].f = r[7].f * r[1].f;
L_12:;
    vigil_tc_move_reg(&r[8].v, r[6].v);
L_13:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 84, 8, 1, 9, NULL);
L_14:;
    tc->ret_count = 0;
    return (vigil_reg_t){0};
    return (vigil_reg_t){0};
}

vigil_reg_t vigil_fn_8(vigil_tc_t *tc, vigil_reg_t arg_0, vigil_reg_t arg_1)
{
    vigil_reg_t r[8];
    memset(r, 0, sizeof(r));
    r[0] = arg_0;
    r[1] = arg_1;
    tc->constants = vigil_fn_constants[8];
    tc->constant_count = vigil_fn_constant_counts[8];

L_0:;
    r[2].i = 0;
L_1:;
    r[3].i = 0;
L_2:;
    { uint16_t _ci = 6; uint8_t _fb = 2, _fc = 2;
      vigil_tc_new_instance(tc, (uint64_t *)r, 4, _ci, _fb, _fc, NULL); }
L_4:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 125, 5, 4, 0, NULL);
L_5:;
    vigil_tc_move_reg(&r[6].v, r[0].v);
L_6:;
    vigil_tc_move_reg(&r[7].v, r[1].v);
L_7:;
    { const vigil_value_t *_sc = tc->constants; size_t _sn = tc->constant_count;
    r[5] = vigil_fn_4(tc, r[5], r[6], r[7]);
    { uint8_t _ri; for (_ri = 1; _ri < tc->ret_count; _ri++) r[5 + _ri].v = tc->ret_buf[_ri]; }
    tc->constants = _sc; tc->constant_count = _sn; }
L_8:;
L_9:;
    tc->ret_count = 1;
    return r[4];
    return (vigil_reg_t){0};
}

vigil_reg_t vigil_fn_9(vigil_tc_t *tc)
{
    vigil_reg_t r[32];
    memset(r, 0, sizeof(r));
    tc->constants = vigil_fn_constants[9];
    tc->constant_count = vigil_fn_constant_counts[9];

L_0:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "Alice", 5, &_s, NULL); vigil_value_init_object(&r[0].v, &_s); }
L_1:;
    r[1].i = (int64_t)30LL;
L_2:;
    { const vigil_value_t *_sc = tc->constants; size_t _sn = tc->constant_count;
    r[0] = vigil_fn_3(tc, r[0], r[1]);
    { uint8_t _ri; for (_ri = 1; _ri < tc->ret_count; _ri++) r[0 + _ri].v = tc->ret_buf[_ri]; }
    tc->constants = _sc; tc->constant_count = _sn; }
L_3:;
    vigil_tc_move_reg(&r[1].v, r[0].v);
L_4:;
    { const vigil_value_t *_sc = tc->constants; size_t _sn = tc->constant_count;
    r[1] = vigil_fn_1(tc, r[1]);
    { uint8_t _ri; for (_ri = 1; _ri < tc->ret_count; _ri++) r[1 + _ri].v = tc->ret_buf[_ri]; }
    tc->constants = _sc; tc->constant_count = _sn; }
L_5:;
    vigil_tc_move_reg(&r[1].v, r[0].v);
L_6:;
    { const vigil_value_t *_sc = tc->constants; size_t _sn = tc->constant_count;
    r[1] = vigil_fn_2(tc, r[1]);
    { uint8_t _ri; for (_ri = 1; _ri < tc->ret_count; _ri++) r[1 + _ri].v = tc->ret_buf[_ri]; }
    tc->constants = _sc; tc->constant_count = _sn; }
L_7:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "", 0, &_s, NULL); vigil_value_init_object(&r[1].v, &_s); }
L_8:;
    vigil_tc_call_native(tc, (uint64_t *)r, 1, 1, 3, NULL);
L_10:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "Bob", 3, &_s, NULL); vigil_value_init_object(&r[1].v, &_s); }
L_11:;
    r[2].i = (int64_t)25LL;
L_12:;
    { const vigil_value_t *_sc = tc->constants; size_t _sn = tc->constant_count;
    r[1] = vigil_fn_3(tc, r[1], r[2]);
    { uint8_t _ri; for (_ri = 1; _ri < tc->ret_count; _ri++) r[1 + _ri].v = tc->ret_buf[_ri]; }
    tc->constants = _sc; tc->constant_count = _sn; }
L_13:;
    vigil_tc_move_reg(&r[2].v, r[1].v);
L_14:;
    { const vigil_value_t *_sc = tc->constants; size_t _sn = tc->constant_count;
    r[2] = vigil_fn_1(tc, r[2]);
    { uint8_t _ri; for (_ri = 1; _ri < tc->ret_count; _ri++) r[2 + _ri].v = tc->ret_buf[_ri]; }
    tc->constants = _sc; tc->constant_count = _sn; }
L_15:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "", 0, &_s, NULL); vigil_value_init_object(&r[2].v, &_s); }
L_16:;
    vigil_tc_call_native(tc, (uint64_t *)r, 2, 1, 7, NULL);
L_18:;
    r[2].f = 10;
L_19:;
    r[3].f = 5;
L_20:;
    { const vigil_value_t *_sc = tc->constants; size_t _sn = tc->constant_count;
    r[2] = vigil_fn_8(tc, r[2], r[3]);
    { uint8_t _ri; for (_ri = 1; _ri < tc->ret_count; _ri++) r[2 + _ri].v = tc->ret_buf[_ri]; }
    tc->constants = _sc; tc->constant_count = _sn; }
L_21:;
    vigil_tc_move_reg(&r[3].v, r[2].v);
L_22:;
    { const vigil_value_t *_sc = tc->constants; size_t _sn = tc->constant_count;
    r[3] = vigil_fn_5(tc, r[3]);
    { uint8_t _ri; for (_ri = 1; _ri < tc->ret_count; _ri++) r[3 + _ri].v = tc->ret_buf[_ri]; }
    tc->constants = _sc; tc->constant_count = _sn; }
L_23:;
    vigil_tc_move_reg(&r[4].v, r[2].v);
L_24:;
    { const vigil_value_t *_sc = tc->constants; size_t _sn = tc->constant_count;
    r[4] = vigil_fn_6(tc, r[4]);
    { uint8_t _ri; for (_ri = 1; _ri < tc->ret_count; _ri++) r[4 + _ri].v = tc->ret_buf[_ri]; }
    tc->constants = _sc; tc->constant_count = _sn; }
L_25:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "Rectangle: ", 11, &_s, NULL); vigil_value_init_object(&r[5].v, &_s); }
L_26:;
    vigil_tc_move_reg(&r[6].v, r[2].v);
L_27:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 83, 6, 6, 0, NULL);
L_28:;
    vigil_tc_to_string(tc, &r[6].v, &r[6].v, NULL);
L_29:;
    vigil_tc_generic_add(tc, &r[7].v, &r[5].v, &r[6].v, NULL);
L_30:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, " x ", 3, &_s, NULL); vigil_value_init_object(&r[8].v, &_s); }
L_31:;
    vigil_tc_generic_add(tc, &r[9].v, &r[7].v, &r[8].v, NULL);
L_32:;
    vigil_tc_move_reg(&r[10].v, r[2].v);
L_33:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 83, 10, 10, 1, NULL);
L_34:;
    vigil_tc_to_string(tc, &r[10].v, &r[10].v, NULL);
L_35:;
    vigil_tc_generic_add(tc, &r[11].v, &r[9].v, &r[10].v, NULL);
L_36:;
    vigil_tc_call_native(tc, (uint64_t *)r, 11, 1, 12, NULL);
L_38:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "Area: ", 6, &_s, NULL); vigil_value_init_object(&r[12].v, &_s); }
L_39:;
    vigil_tc_move_reg(&r[13].v, r[3].v);
L_40:;
    vigil_tc_to_string(tc, &r[13].v, &r[13].v, NULL);
L_41:;
    vigil_tc_generic_add(tc, &r[14].v, &r[12].v, &r[13].v, NULL);
L_42:;
    vigil_tc_call_native(tc, (uint64_t *)r, 14, 1, 14, NULL);
L_44:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "Perimeter: ", 11, &_s, NULL); vigil_value_init_object(&r[15].v, &_s); }
L_45:;
    vigil_tc_move_reg(&r[16].v, r[4].v);
L_46:;
    vigil_tc_to_string(tc, &r[16].v, &r[16].v, NULL);
L_47:;
    vigil_tc_generic_add(tc, &r[17].v, &r[15].v, &r[16].v, NULL);
L_48:;
    vigil_tc_call_native(tc, (uint64_t *)r, 17, 1, 16, NULL);
L_50:;
    vigil_tc_move_reg(&r[18].v, r[2].v);
L_51:;
    r[19].f = 2;
L_52:;
    { const vigil_value_t *_sc = tc->constants; size_t _sn = tc->constant_count;
    r[18] = vigil_fn_7(tc, r[18], r[19]);
    { uint8_t _ri; for (_ri = 1; _ri < tc->ret_count; _ri++) r[18 + _ri].v = tc->ret_buf[_ri]; }
    tc->constants = _sc; tc->constant_count = _sn; }
L_53:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "\nAfter scaling by 2:", 20, &_s, NULL); vigil_value_init_object(&r[20].v, &_s); }
L_54:;
    vigil_tc_call_native(tc, (uint64_t *)r, 20, 1, 19, NULL);
L_56:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "Rectangle: ", 11, &_s, NULL); vigil_value_init_object(&r[21].v, &_s); }
L_57:;
    vigil_tc_move_reg(&r[22].v, r[2].v);
L_58:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 83, 22, 22, 0, NULL);
L_59:;
    vigil_tc_to_string(tc, &r[22].v, &r[22].v, NULL);
L_60:;
    vigil_tc_generic_add(tc, &r[23].v, &r[21].v, &r[22].v, NULL);
L_61:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, " x ", 3, &_s, NULL); vigil_value_init_object(&r[24].v, &_s); }
L_62:;
    vigil_tc_generic_add(tc, &r[25].v, &r[23].v, &r[24].v, NULL);
L_63:;
    vigil_tc_move_reg(&r[26].v, r[2].v);
L_64:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 83, 26, 26, 1, NULL);
L_65:;
    vigil_tc_to_string(tc, &r[26].v, &r[26].v, NULL);
L_66:;
    vigil_tc_generic_add(tc, &r[27].v, &r[25].v, &r[26].v, NULL);
L_67:;
    vigil_tc_call_native(tc, (uint64_t *)r, 27, 1, 22, NULL);
L_69:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "Area: ", 6, &_s, NULL); vigil_value_init_object(&r[28].v, &_s); }
L_70:;
    vigil_tc_move_reg(&r[29].v, r[2].v);
L_71:;
    { const vigil_value_t *_sc = tc->constants; size_t _sn = tc->constant_count;
    r[29] = vigil_fn_5(tc, r[29]);
    { uint8_t _ri; for (_ri = 1; _ri < tc->ret_count; _ri++) r[29 + _ri].v = tc->ret_buf[_ri]; }
    tc->constants = _sc; tc->constant_count = _sn; }
L_72:;
    vigil_tc_to_string(tc, &r[29].v, &r[29].v, NULL);
L_73:;
    vigil_tc_generic_add(tc, &r[30].v, &r[28].v, &r[29].v, NULL);
L_74:;
    vigil_tc_call_native(tc, (uint64_t *)r, 30, 1, 24, NULL);
L_76:;
    r[31].i = (int64_t)0LL;
L_77:;
L_78:;
    tc->ret_count = 1;
    return r[31];
    return (vigil_reg_t){0};
}

