/* vigil_editor.c — editor integration install/uninstall. */

#include "vigil/editor.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "platform/platform.h"

/* ── supported editors ───────────────────────────────────────────── */

static const char *const supported_editors[] = {"vim", "vscode", NULL};

VIGIL_API const char *const *vigil_editor_supported(void)
{
    return supported_editors;
}

VIGIL_API int vigil_editor_is_supported(const char *name)
{
    const char *const *p;
    if (!name)
        return 0;
    for (p = supported_editors; *p; p++)
        if (strcmp(*p, name) == 0)
            return 1;
    return 0;
}

/* ── path helpers ────────────────────────────────────────────────── */

static int path_join(char *buf, size_t cap, const char *a, const char *b)
{
    size_t la = strlen(a), lb = strlen(b);
    if (la + 1 + lb + 1 > cap)
        return 0;
    memcpy(buf, a, la);
    buf[la] = '/';
    memcpy(buf + la + 1, b, lb);
    buf[la + 1 + lb] = '\0';
    return 1;
}

static int mkdirs(const char *path)
{
    char tmp[1024];
    size_t len = strlen(path);
    size_t i;
    if (len >= sizeof(tmp))
        return 0;
    memcpy(tmp, path, len + 1);
    for (i = 1; i < len; i++)
    {
        if (tmp[i] == '/')
        {
            tmp[i] = '\0';
            vigil_platform_mkdir(tmp, NULL);
            tmp[i] = '/';
        }
    }
    vigil_platform_mkdir(tmp, NULL);
    return 1;
}

static int write_file(const char *path, const char *content)
{
    FILE *f = fopen(path, "wb");
    if (!f)
        return 0;
    fwrite(content, 1, strlen(content), f);
    fclose(f);
    return 1;
}

static int file_exists(const char *path)
{
    FILE *f = fopen(path, "rb");
    if (!f)
        return 0;
    fclose(f);
    return 1;
}

/* ── vim ─────────────────────────────────────────────────────────── */

static const char *vim_ft_relpath = ".vim/after/ftdetect/vigil.vim";
static const char *vim_syn_relpath = ".vim/after/syntax/vigil.vim";

static const char vim_ft_content[] = "\" Vigil filetype detection (auto-generated by 'vigil editor install vim')\n"
                                     "autocmd BufRead,BufNewFile *.vigil set filetype=vigil\n";

static const char vim_syn_content[] =
    "\" Vigil syntax highlighting (auto-generated by 'vigil editor install vim')\n"
    "if exists('b:current_syntax') | finish | endif\n"
    "syn keyword vigilKeyword fn return if else for while break continue import const\n"
    "syn keyword vigilKeyword defer guard switch case default enum class interface\n"
    "syn keyword vigilKeyword pub new self true false nil ok err in\n"
    "syn keyword vigilType i32 i64 f64 u8 u32 u64 bool string void array map err\n"
    "syn match vigilComment '//.*$'\n"
    "syn region vigilString start='\"' end='\"' skip='\\\\\"'\n"
    "hi def link vigilKeyword Keyword\n"
    "hi def link vigilType Type\n"
    "hi def link vigilComment Comment\n"
    "hi def link vigilString String\n"
    "let b:current_syntax = 'vigil'\n";

/* ── vscode ──────────────────────────────────────────────────────── */

static const char *vscode_ext_relpath = ".vscode/extensions/vigil-lang";
static const char *vscode_pkg_relname = "package.json";

static void vscode_pkg_content(char *buf, size_t cap, const char *vigil_bin)
{
    snprintf(buf, cap,
             "{\n"
             "  \"name\": \"vigil-lang\",\n"
             "  \"displayName\": \"Vigil\",\n"
             "  \"description\": \"Vigil language support\",\n"
             "  \"version\": \"0.1.0\",\n"
             "  \"publisher\": \"local\",\n"
             "  \"engines\": { \"vscode\": \"^1.75.0\" },\n"
             "  \"activationEvents\": [\"onLanguage:vigil\"],\n"
             "  \"contributes\": {\n"
             "    \"languages\": [{\n"
             "      \"id\": \"vigil\",\n"
             "      \"extensions\": [\".vigil\"],\n"
             "      \"configuration\": \"./language-configuration.json\"\n"
             "    }]\n"
             "  },\n"
             "  \"main\": \"./extension.js\",\n"
             "  \"dependencies\": {\n"
             "    \"vscode-languageclient\": \"^9.0.1\"\n"
             "  }\n"
             "}\n");
    (void)vigil_bin;
}

static void vscode_ext_content(char *buf, size_t cap, const char *vigil_bin)
{
    snprintf(buf, cap,
             "const vscode = require('vscode');\n"
             "const { LanguageClient } = require('vscode-languageclient/node');\n"
             "let client;\n"
             "function activate(context) {\n"
             "  client = new LanguageClient('vigil', 'Vigil LSP',\n"
             "    { command: '%s', args: ['lsp'] },\n"
             "    { documentSelector: [{ scheme: 'file', language: 'vigil' }] });\n"
             "  client.start();\n"
             "}\n"
             "function deactivate() { return client && client.stop(); }\n"
             "module.exports = { activate, deactivate };\n",
             vigil_bin);
}

static const char vscode_langconf[] = "{\n"
                                      "  \"comments\": { \"lineComment\": \"//\" },\n"
                                      "  \"brackets\": [[\"{\", \"}\"], [\"[\", \"]\"], [\"(\", \")\"]],\n"
                                      "  \"autoClosingPairs\": [\n"
                                      "    { \"open\": \"{\", \"close\": \"}\" },\n"
                                      "    { \"open\": \"[\", \"close\": \"]\" },\n"
                                      "    { \"open\": \"(\", \"close\": \")\" },\n"
                                      "    { \"open\": \"\\\"\", \"close\": \"\\\"\" }\n"
                                      "  ]\n"
                                      "}\n";

/* ── install / uninstall dispatch ────────────────────────────────── */

static vigil_editor_result_t result_ok(const char *msg)
{
    vigil_editor_result_t r = {VIGIL_STATUS_OK, {0}};
    snprintf(r.message, sizeof(r.message), "%s", msg);
    return r;
}

static vigil_editor_result_t result_err(const char *msg)
{
    vigil_editor_result_t r = {VIGIL_STATUS_INTERNAL, {0}};
    snprintf(r.message, sizeof(r.message), "%s", msg);
    return r;
}

/* vim install: config_home is $HOME */
static vigil_editor_result_t install_vim(const char *vigil_bin, const char *home)
{
    char ft_path[1024], syn_path[1024], dir[1024];
    (void)vigil_bin;

    if (!path_join(ft_path, sizeof(ft_path), home, vim_ft_relpath))
        return result_err("path too long");
    if (!path_join(syn_path, sizeof(syn_path), home, vim_syn_relpath))
        return result_err("path too long");

    memcpy(dir, ft_path, strlen(ft_path) + 1);
    *strrchr(dir, '/') = '\0';
    mkdirs(dir);
    memcpy(dir, syn_path, strlen(syn_path) + 1);
    *strrchr(dir, '/') = '\0';
    mkdirs(dir);

    printf("Creating %s\n", ft_path);
    if (!write_file(ft_path, vim_ft_content))
        return result_err("failed to write filetype config");
    printf("Creating %s\n", syn_path);
    if (!write_file(syn_path, vim_syn_content))
        return result_err("failed to write syntax config");

    return result_ok("Done. To undo: vigil editor uninstall vim");
}

static vigil_editor_result_t uninstall_vim(const char *home)
{
    char ft_path[1024], syn_path[1024];
    path_join(ft_path, sizeof(ft_path), home, vim_ft_relpath);
    path_join(syn_path, sizeof(syn_path), home, vim_syn_relpath);
    if (file_exists(ft_path))
    {
        printf("Removing %s\n", ft_path);
        remove(ft_path);
    }
    if (file_exists(syn_path))
    {
        printf("Removing %s\n", syn_path);
        remove(syn_path);
    }
    return result_ok("Done.");
}

static int is_installed_vim(const char *home)
{
    char path[1024];
    path_join(path, sizeof(path), home, vim_ft_relpath);
    return file_exists(path);
}

/* vscode install */
static vigil_editor_result_t install_vscode(const char *vigil_bin, const char *home)
{
    char ext_dir[1024], pkg_path[1024], ext_path[1024], lang_path[1024], content[2048];

    if (!path_join(ext_dir, sizeof(ext_dir), home, vscode_ext_relpath))
        return result_err("path too long");
    mkdirs(ext_dir);

    path_join(pkg_path, sizeof(pkg_path), ext_dir, vscode_pkg_relname);
    path_join(ext_path, sizeof(ext_path), ext_dir, "extension.js");
    path_join(lang_path, sizeof(lang_path), ext_dir, "language-configuration.json");

    vscode_pkg_content(content, sizeof(content), vigil_bin);
    printf("Creating %s\n", pkg_path);
    if (!write_file(pkg_path, content))
        return result_err("failed to write package.json");

    vscode_ext_content(content, sizeof(content), vigil_bin);
    printf("Creating %s\n", ext_path);
    if (!write_file(ext_path, content))
        return result_err("failed to write extension.js");

    printf("Creating %s\n", lang_path);
    if (!write_file(lang_path, vscode_langconf))
        return result_err("failed to write language-configuration.json");

    printf("Running npm install in %s\n", ext_dir);
    {
        char cmd[1200];
        snprintf(cmd, sizeof(cmd), "cd \"%s\" && npm install --silent 2>&1", ext_dir);
        int rc = system(cmd);
        if (rc != 0)
            return result_err("npm install failed — is Node.js installed?");
    }

    return result_ok("Done. Reload VS Code and open a .vigil file.\n"
                     "To undo: vigil editor uninstall vscode");
}

static vigil_editor_result_t uninstall_vscode(const char *home)
{
    char ext_dir[1024], path[1024];
    path_join(ext_dir, sizeof(ext_dir), home, vscode_ext_relpath);
    const char *files[] = {"package.json", "extension.js", "language-configuration.json", "package-lock.json", NULL};
    for (const char *const *f = files; *f; f++)
    {
        path_join(path, sizeof(path), ext_dir, *f);
        if (file_exists(path))
        {
            printf("Removing %s\n", path);
            remove(path);
        }
    }
    /* Remove node_modules */
    path_join(path, sizeof(path), ext_dir, "node_modules");
    {
        char cmd[1200];
        snprintf(cmd, sizeof(cmd), "rm -rf \"%s\" 2>/dev/null", path);
        printf("Removing %s\n", path);
        system(cmd);
    }
    return result_ok("Done.");
}

static int is_installed_vscode(const char *home)
{
    char path[1024];
    path_join(path, sizeof(path), home, vscode_ext_relpath);
    path_join(path, sizeof(path), path, vscode_pkg_relname);
    return file_exists(path);
}

/* ── public dispatch ─────────────────────────────────────────────── */

VIGIL_API vigil_editor_result_t vigil_editor_install(const char *name, const char *vigil_bin, const char *config_home)
{
    if (!name || !vigil_bin || !config_home)
        return result_err("invalid arguments");
    if (strcmp(name, "vim") == 0)
        return install_vim(vigil_bin, config_home);
    if (strcmp(name, "vscode") == 0)
        return install_vscode(vigil_bin, config_home);
    return result_err("unknown editor");
}

VIGIL_API vigil_editor_result_t vigil_editor_uninstall(const char *name, const char *config_home)
{
    if (!name || !config_home)
        return result_err("invalid arguments");
    if (strcmp(name, "vim") == 0)
        return uninstall_vim(config_home);
    if (strcmp(name, "vscode") == 0)
        return uninstall_vscode(config_home);
    return result_err("unknown editor");
}

VIGIL_API int vigil_editor_is_installed(const char *name, const char *config_home)
{
    if (!name || !config_home)
        return 0;
    if (strcmp(name, "vim") == 0)
        return is_installed_vim(config_home);
    if (strcmp(name, "vscode") == 0)
        return is_installed_vscode(config_home);
    return 0;
}
