/* vigil_editor.c — editor integration install/uninstall. */

#include "vigil/editor.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "platform/platform.h"

/* ── supported editors ───────────────────────────────────────────── */

static const char *const supported_editors[] = {"vim", "vscode", NULL};

VIGIL_API const char *const *vigil_editor_supported(void)
{
    return supported_editors;
}

VIGIL_API int vigil_editor_is_supported(const char *name)
{
    const char *const *p;
    if (!name)
        return 0;
    for (p = supported_editors; *p; p++)
        if (strcmp(*p, name) == 0)
            return 1;
    return 0;
}

/* ── path helpers using platform layer ───────────────────────────── */

static int pjoin(char *buf, size_t cap, const char *a, const char *b)
{
    return vigil_platform_path_join(a, b, buf, cap, NULL) == VIGIL_STATUS_OK;
}

static int pexists(const char *path)
{
    int exists = 0;
    vigil_platform_file_exists(path, &exists);
    return exists;
}

static int pwrite(const char *path, const char *content)
{
    return vigil_platform_write_file(path, content, strlen(content), NULL) == VIGIL_STATUS_OK;
}

static void premove(const char *path)
{
    if (pexists(path))
    {
        printf("Removing %s\n", path);
        vigil_platform_remove(path, NULL);
    }
}

/* ── result helpers ──────────────────────────────────────────────── */

static vigil_editor_result_t result_ok(const char *msg)
{
    vigil_editor_result_t r = {VIGIL_STATUS_OK, {0}};
    snprintf(r.message, sizeof(r.message), "%s", msg);
    return r;
}

static vigil_editor_result_t result_err(const char *msg)
{
    vigil_editor_result_t r = {VIGIL_STATUS_INTERNAL, {0}};
    snprintf(r.message, sizeof(r.message), "%s", msg);
    return r;
}

/* ── vim ─────────────────────────────────────────────────────────── */

static const char vim_ft_content[] = "\" Vigil filetype detection (auto-generated by 'vigil editor install vim')\n"
                                     "autocmd BufRead,BufNewFile *.vigil set filetype=vigil\n";

static const char vim_syn_content[] =
    "\" Vigil syntax highlighting (auto-generated by 'vigil editor install vim')\n"
    "if exists('b:current_syntax') | finish | endif\n"
    "syn keyword vigilKeyword fn return if else for while break continue import const\n"
    "syn keyword vigilKeyword defer guard switch case default enum class interface\n"
    "syn keyword vigilKeyword pub new self true false nil ok err in\n"
    "syn keyword vigilType i32 i64 f64 u8 u32 u64 bool string void array map err\n"
    "syn match vigilComment '//.*$'\n"
    "syn region vigilString start='\"' end='\"' skip='\\\\\"'\n"
    "hi def link vigilKeyword Keyword\n"
    "hi def link vigilType Type\n"
    "hi def link vigilComment Comment\n"
    "hi def link vigilString String\n"
    "let b:current_syntax = 'vigil'\n";

static vigil_editor_result_t install_vim(const char *vigil_bin, const char *home)
{
    char ft_path[1024], syn_path[1024], dir[1024];
    (void)vigil_bin;

    if (!pjoin(dir, sizeof(dir), home, ".vim") || !pjoin(dir, sizeof(dir), dir, "after") ||
        !pjoin(dir, sizeof(dir), dir, "ftdetect"))
        return result_err("path too long");
    vigil_platform_mkdir_p(dir, NULL);
    if (!pjoin(ft_path, sizeof(ft_path), dir, "vigil.vim"))
        return result_err("path too long");

    if (!pjoin(dir, sizeof(dir), home, ".vim") || !pjoin(dir, sizeof(dir), dir, "after") ||
        !pjoin(dir, sizeof(dir), dir, "syntax"))
        return result_err("path too long");
    vigil_platform_mkdir_p(dir, NULL);
    if (!pjoin(syn_path, sizeof(syn_path), dir, "vigil.vim"))
        return result_err("path too long");

    printf("Creating %s\n", ft_path);
    if (!pwrite(ft_path, vim_ft_content))
        return result_err("failed to write filetype config");
    printf("Creating %s\n", syn_path);
    if (!pwrite(syn_path, vim_syn_content))
        return result_err("failed to write syntax config");

    return result_ok("Done. To undo: vigil editor uninstall vim");
}

static vigil_editor_result_t uninstall_vim(const char *home)
{
    char path[1024], dir[1024];
    if (pjoin(dir, sizeof(dir), home, ".vim") && pjoin(dir, sizeof(dir), dir, "after"))
    {
        char sub[1024];
        if (pjoin(sub, sizeof(sub), dir, "ftdetect") && pjoin(path, sizeof(path), sub, "vigil.vim"))
            premove(path);
        if (pjoin(sub, sizeof(sub), dir, "syntax") && pjoin(path, sizeof(path), sub, "vigil.vim"))
            premove(path);
    }
    return result_ok("Done.");
}

static int is_installed_vim(const char *home)
{
    char path[1024], dir[1024];
    if (!pjoin(dir, sizeof(dir), home, ".vim") || !pjoin(dir, sizeof(dir), dir, "after") ||
        !pjoin(dir, sizeof(dir), dir, "ftdetect") || !pjoin(path, sizeof(path), dir, "vigil.vim"))
        return 0;
    return pexists(path);
}

/* ── vscode ──────────────────────────────────────────────────────── */

static void vscode_pkg_content(char *buf, size_t cap)
{
    snprintf(buf, cap,
             "{\n"
             "  \"name\": \"vigil-lang\",\n"
             "  \"displayName\": \"Vigil\",\n"
             "  \"description\": \"Vigil language support\",\n"
             "  \"version\": \"0.1.0\",\n"
             "  \"publisher\": \"local\",\n"
             "  \"engines\": { \"vscode\": \"^1.75.0\" },\n"
             "  \"activationEvents\": [\"onLanguage:vigil\"],\n"
             "  \"contributes\": {\n"
             "    \"languages\": [{\n"
             "      \"id\": \"vigil\",\n"
             "      \"extensions\": [\".vigil\"],\n"
             "      \"configuration\": \"./language-configuration.json\"\n"
             "    }]\n"
             "  },\n"
             "  \"main\": \"./extension.js\",\n"
             "  \"dependencies\": {\n"
             "    \"vscode-languageclient\": \"^9.0.1\"\n"
             "  }\n"
             "}\n");
}

static void vscode_ext_content(char *buf, size_t cap, const char *vigil_bin)
{
    snprintf(buf, cap,
             "const vscode = require('vscode');\n"
             "const { LanguageClient } = require('vscode-languageclient/node');\n"
             "let client;\n"
             "function activate(context) {\n"
             "  const output = vscode.window.createOutputChannel('Vigil');\n"
             "  output.appendLine('Vigil extension activated');\n"
             "  client = new LanguageClient('vigil', 'Vigil LSP',\n"
             "    { command: '%s', args: ['lsp'] },\n"
             "    { documentSelector: [{ scheme: 'file', language: 'vigil' }],\n"
             "      outputChannel: output });\n"
             "  context.subscriptions.push(client.start());\n"
             "}\n"
             "function deactivate() { return client && client.stop(); }\n"
             "module.exports = { activate, deactivate };\n",
             vigil_bin);
}

static const char vscode_langconf[] = "{\n"
                                      "  \"comments\": { \"lineComment\": \"//\" },\n"
                                      "  \"brackets\": [[\"{\", \"}\"], [\"[\", \"]\"], [\"(\", \")\"]],\n"
                                      "  \"autoClosingPairs\": [\n"
                                      "    { \"open\": \"{\", \"close\": \"}\" },\n"
                                      "    { \"open\": \"[\", \"close\": \"]\" },\n"
                                      "    { \"open\": \"(\", \"close\": \")\" },\n"
                                      "    { \"open\": \"\\\"\", \"close\": \"\\\"\" }\n"
                                      "  ]\n"
                                      "}\n";

static int vscode_ext_dir(char *buf, size_t cap, const char *home)
{
    return pjoin(buf, cap, home, ".vscode") && pjoin(buf, cap, buf, "extensions") && pjoin(buf, cap, buf, "vigil-lang");
}

static vigil_editor_result_t install_vscode(const char *vigil_bin, const char *home)
{
    char ext_dir[1024], path[1024], content[2048];

    if (!vscode_ext_dir(ext_dir, sizeof(ext_dir), home))
        return result_err("path too long");
    vigil_platform_mkdir_p(ext_dir, NULL);

    if (!pjoin(path, sizeof(path), ext_dir, "package.json"))
        return result_err("path too long");
    vscode_pkg_content(content, sizeof(content));
    printf("Creating %s\n", path);
    if (!pwrite(path, content))
        return result_err("failed to write package.json");

    if (!pjoin(path, sizeof(path), ext_dir, "extension.js"))
        return result_err("path too long");
    vscode_ext_content(content, sizeof(content), vigil_bin);
    printf("Creating %s\n", path);
    if (!pwrite(path, content))
        return result_err("failed to write extension.js");

    if (!pjoin(path, sizeof(path), ext_dir, "language-configuration.json"))
        return result_err("path too long");
    printf("Creating %s\n", path);
    if (!pwrite(path, vscode_langconf))
        return result_err("failed to write language-configuration.json");

    /* Install npm dependencies */
    printf("Running npm install in %s\n", ext_dir);
    {
        char cmd[1200];
#ifdef _WIN32
        snprintf(cmd, sizeof(cmd), "cd /d \"%s\" && npm install --silent 2>nul", ext_dir);
#else
        snprintf(cmd, sizeof(cmd), "cd \"%s\" && npm install --silent 2>&1", ext_dir);
#endif
        int rc = system(cmd);
        if (rc != 0)
            return result_err("npm install failed — is Node.js installed?");
    }

    return result_ok("Done. Reload VS Code and open a .vigil file.\n"
                     "To undo: vigil editor uninstall vscode");
}

static vigil_editor_result_t uninstall_vscode(const char *home)
{
    char ext_dir[1024], path[1024];
    if (!vscode_ext_dir(ext_dir, sizeof(ext_dir), home))
        return result_ok("Done.");

    const char *files[] = {"package.json", "extension.js", "language-configuration.json", "package-lock.json", NULL};
    for (const char *const *f = files; *f; f++)
    {
        if (pjoin(path, sizeof(path), ext_dir, *f))
            premove(path);
    }
    /* Remove node_modules */
    if (pjoin(path, sizeof(path), ext_dir, "node_modules"))
    {
        printf("Removing %s\n", path);
        vigil_platform_remove_all(path, NULL);
    }
    return result_ok("Done.");
}

static int is_installed_vscode(const char *home)
{
    char path[1024], ext_dir[1024];
    if (!vscode_ext_dir(ext_dir, sizeof(ext_dir), home))
        return 0;
    if (!pjoin(path, sizeof(path), ext_dir, "package.json"))
        return 0;
    return pexists(path);
}

/* ── public dispatch ─────────────────────────────────────────────── */

VIGIL_API vigil_editor_result_t vigil_editor_install(const char *name, const char *vigil_bin, const char *home)
{
    if (!name || !vigil_bin || !home)
        return result_err("invalid arguments");
    if (strcmp(name, "vim") == 0)
        return install_vim(vigil_bin, home);
    if (strcmp(name, "vscode") == 0)
        return install_vscode(vigil_bin, home);
    return result_err("unknown editor");
}

VIGIL_API vigil_editor_result_t vigil_editor_uninstall(const char *name, const char *home)
{
    if (!name || !home)
        return result_err("invalid arguments");
    if (strcmp(name, "vim") == 0)
        return uninstall_vim(home);
    if (strcmp(name, "vscode") == 0)
        return uninstall_vscode(home);
    return result_err("unknown editor");
}

VIGIL_API int vigil_editor_is_installed(const char *name, const char *home)
{
    if (!name || !home)
        return 0;
    if (strcmp(name, "vim") == 0)
        return is_installed_vim(home);
    if (strcmp(name, "vscode") == 0)
        return is_installed_vscode(home);
    return 0;
}
