/* vigil_editor.c — editor integration install/uninstall. */

#include "vigil/editor.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#if defined(__APPLE__)
#include <TargetConditionals.h>
#endif

#include "platform/platform.h"

/* ── path helpers using platform layer ───────────────────────────── */

static int pjoin(char *buf, size_t cap, const char *a, const char *b)
{
    return vigil_platform_path_join(a, b, buf, cap, NULL) == VIGIL_STATUS_OK;
}

static int pexists(const char *path)
{
    int exists = 0;
    vigil_platform_file_exists(path, &exists);
    return exists;
}

static int pwrite(const char *path, const char *content)
{
    return vigil_platform_write_file(path, content, strlen(content), NULL) == VIGIL_STATUS_OK;
}

static int pwrite_len(const char *path, const char *content, size_t length)
{
    return vigil_platform_write_file(path, content, length, NULL) == VIGIL_STATUS_OK;
}

static int pread(const char *path, char **out_content, size_t *out_length)
{
    char *content = NULL;
    size_t length = 0;
    if (vigil_platform_read_file(NULL, path, &content, &length, NULL) != VIGIL_STATUS_OK)
        return 0;
    *out_content = content;
    *out_length = length;
    return 1;
}

static void premove(const char *path)
{
    if (pexists(path))
    {
        printf("Removing %s\n", path);
        vigil_platform_remove(path, NULL);
    }
}

/* ── result helpers ──────────────────────────────────────────────── */

static vigil_editor_result_t result_ok(const char *msg)
{
    vigil_editor_result_t r = {VIGIL_STATUS_OK, {0}};
    snprintf(r.message, sizeof(r.message), "%s", msg);
    return r;
}

static vigil_editor_result_t result_err(const char *msg)
{
    vigil_editor_result_t r = {VIGIL_STATUS_INTERNAL, {0}};
    snprintf(r.message, sizeof(r.message), "%s", msg);
    return r;
}

/* ── config path helpers ─────────────────────────────────────────── */

static int nvim_root(char *buf, size_t cap, const char *home)
{
#ifdef _WIN32
    if (!pjoin(buf, cap, home, "AppData"))
        return 0;
    if (!pjoin(buf, cap, buf, "Local"))
        return 0;
    return pjoin(buf, cap, buf, "nvim");
#else
    if (!pjoin(buf, cap, home, ".config"))
        return 0;
    return pjoin(buf, cap, buf, "nvim");
#endif
}

static int sublime_root(char *buf, size_t cap, const char *home)
{
#ifdef _WIN32
    if (!pjoin(buf, cap, home, "AppData"))
        return 0;
    if (!pjoin(buf, cap, buf, "Roaming"))
        return 0;
    if (!pjoin(buf, cap, buf, "Sublime Text"))
        return 0;
    return pjoin(buf, cap, buf, "Packages");
#elif defined(__APPLE__)
    if (!pjoin(buf, cap, home, "Library"))
        return 0;
    if (!pjoin(buf, cap, buf, "Application Support"))
        return 0;
    if (!pjoin(buf, cap, buf, "Sublime Text"))
        return 0;
    return pjoin(buf, cap, buf, "Packages");
#else
    if (!pjoin(buf, cap, home, ".config"))
        return 0;
    if (!pjoin(buf, cap, buf, "sublime-text"))
        return 0;
    return pjoin(buf, cap, buf, "Packages");
#endif
}

static int emacs_dir(char *buf, size_t cap, const char *home)
{
    return pjoin(buf, cap, home, ".emacs.d");
}

/* ── shared language content ─────────────────────────────────────── */

static const char vim_ft_content[] = "\" Vigil filetype detection (auto-generated by 'vigil editor install vim')\n"
                                     "autocmd BufRead,BufNewFile *.vigil set filetype=vigil\n";

static const char vim_syn_content[] =
    "\" Vigil syntax highlighting (auto-generated by 'vigil editor install vim')\n"
    "if exists('b:current_syntax') | finish | endif\n"
    "syn keyword vigilKeyword fn return if else for while break continue import const\n"
    "syn keyword vigilKeyword defer guard switch case default enum class interface\n"
    "syn keyword vigilKeyword pub new self true false nil ok err in\n"
    "syn keyword vigilType i32 i64 f64 u8 u32 u64 bool string void array map err\n"
    "syn match vigilComment '//.*$'\n"
    "syn region vigilString start='\"' end='\"' skip='\\\\\"'\n"
    "hi def link vigilKeyword Keyword\n"
    "hi def link vigilType Type\n"
    "hi def link vigilComment Comment\n"
    "hi def link vigilString String\n"
    "let b:current_syntax = 'vigil'\n";

static const char emacs_mode_content[] =
    ";;; vigil-mode.el --- Major mode for Vigil -*- lexical-binding: t; -*-\n"
    "\n"
    "(defvar vigil-mode-syntax-table\n"
    "  (let ((table (make-syntax-table)))\n"
    "    (modify-syntax-entry ?/ \". 124b\" table)\n"
    "    (modify-syntax-entry ?* \". 23\" table)\n"
    "    (modify-syntax-entry ?\\n \"> b\" table)\n"
    "    (modify-syntax-entry ?_ \"w\" table)\n"
    "    table))\n"
    "\n"
    "(defconst vigil-font-lock-keywords\n"
    "  "
    "'((\"\\\\_<\\\\(fn\\\\|return\\\\|if\\\\|else\\\\|for\\\\|while\\\\|break\\\\|continue\\\\|import\\\\|const\\\\|"
    "defer\\\\|guard\\\\|switch\\\\|case\\\\|default\\\\|enum\\\\|class\\\\|interface\\\\|pub\\\\|new\\\\|self\\\\|"
    "true\\\\|false\\\\|nil\\\\|ok\\\\|err\\\\|in\\\\)\\\\_>\" . font-lock-keyword-face)\n"
    "    "
    "(\"\\\\_<\\\\(i32\\\\|i64\\\\|f64\\\\|u8\\\\|u32\\\\|u64\\\\|bool\\\\|string\\\\|void\\\\|array\\\\|map\\\\|"
    "err\\\\)\\\\_>\" . font-lock-type-face)))\n"
    "\n"
    "(define-derived-mode vigil-mode prog-mode \"Vigil\"\n"
    "  \"Major mode for editing Vigil files.\"\n"
    "  :syntax-table vigil-mode-syntax-table\n"
    "  (setq-local comment-start \"// \")\n"
    "  (setq-local comment-end \"\")\n"
    "  (setq-local font-lock-defaults '(vigil-font-lock-keywords)))\n"
    "\n"
    "(provide 'vigil-mode)\n"
    ";;; vigil-mode.el ends here\n";

static const char sublime_syntax_content[] =
    "%YAML 1.2\n"
    "---\n"
    "name: Vigil\n"
    "file_extensions:\n"
    "  - vigil\n"
    "scope: source.vigil\n"
    "contexts:\n"
    "  main:\n"
    "    - match: //.*$\n"
    "      scope: comment.line.double-slash.vigil\n"
    "    - match: '\"'\n"
    "      scope: punctuation.definition.string.begin.vigil\n"
    "      push: string\n"
    "    - match: "
    "'\\\\b(fn|return|if|else|for|while|break|continue|import|const|defer|guard|switch|case|default|enum|class|"
    "interface|pub|new|self|true|false|nil|ok|err|in)\\\\b'\n"
    "      scope: keyword.control.vigil\n"
    "    - match: '\\\\b(i32|i64|f64|u8|u32|u64|bool|string|void|array|map|err)\\\\b'\n"
    "      scope: storage.type.vigil\n"
    "  string:\n"
    "    - match: '\\\\\\\\.'\n"
    "      scope: constant.character.escape.vigil\n"
    "    - match: '\"'\n"
    "      scope: punctuation.definition.string.end.vigil\n"
    "      pop: true\n"
    "    - match: '.'\n"
    "      scope: string.quoted.double.vigil\n";

static int ensure_dir(const char *path)
{
    return vigil_platform_mkdir_p(path, NULL) == VIGIL_STATUS_OK;
}

static vigil_editor_result_t install_vim_family(const char *editor_name, const char *root)
{
    char ft_path[1024], syn_path[1024], dir[1024];
    if (!pjoin(dir, sizeof(dir), root, "after") || !pjoin(dir, sizeof(dir), dir, "ftdetect"))
        return result_err("path too long");
    if (!ensure_dir(dir))
        return result_err("failed to create filetype directory");
    if (!pjoin(ft_path, sizeof(ft_path), dir, "vigil.vim"))
        return result_err("path too long");

    if (!pjoin(dir, sizeof(dir), root, "after") || !pjoin(dir, sizeof(dir), dir, "syntax"))
        return result_err("path too long");
    if (!ensure_dir(dir))
        return result_err("failed to create syntax directory");
    if (!pjoin(syn_path, sizeof(syn_path), dir, "vigil.vim"))
        return result_err("path too long");

    printf("Creating %s\n", ft_path);
    if (!pwrite(ft_path, vim_ft_content))
        return result_err("failed to write filetype config");
    printf("Creating %s\n", syn_path);
    if (!pwrite(syn_path, vim_syn_content))
        return result_err("failed to write syntax config");

    {
        char message[256];
        snprintf(message, sizeof(message), "Done. To undo: vigil editor uninstall %s", editor_name);
        return result_ok(message);
    }
}

static vigil_editor_result_t uninstall_vim_family(const char *root)
{
    char path[1024], dir[1024];
    if (pjoin(dir, sizeof(dir), root, "after"))
    {
        char sub[1024];
        if (pjoin(sub, sizeof(sub), dir, "ftdetect") && pjoin(path, sizeof(path), sub, "vigil.vim"))
            premove(path);
        if (pjoin(sub, sizeof(sub), dir, "syntax") && pjoin(path, sizeof(path), sub, "vigil.vim"))
            premove(path);
    }
    return result_ok("Done.");
}

static int is_installed_vim_family(const char *root)
{
    char path[1024], dir[1024];
    if (!pjoin(dir, sizeof(dir), root, "after") || !pjoin(dir, sizeof(dir), dir, "ftdetect") ||
        !pjoin(path, sizeof(path), dir, "vigil.vim"))
        return 0;
    return pexists(path);
}

/* ── vim / nvim ──────────────────────────────────────────────────── */

static vigil_editor_result_t install_vim(const char *vigil_bin, const char *home)
{
    char root[1024];
    (void)vigil_bin;
    if (!pjoin(root, sizeof(root), home, ".vim"))
        return result_err("path too long");
    return install_vim_family("vim", root);
}

static vigil_editor_result_t uninstall_vim(const char *home)
{
    char root[1024];
    if (!pjoin(root, sizeof(root), home, ".vim"))
        return result_ok("Done.");
    return uninstall_vim_family(root);
}

static int is_installed_vim(const char *home)
{
    char root[1024];
    if (!pjoin(root, sizeof(root), home, ".vim"))
        return 0;
    return is_installed_vim_family(root);
}

static vigil_editor_result_t install_nvim(const char *vigil_bin, const char *home)
{
    char root[1024];
    (void)vigil_bin;
    if (!nvim_root(root, sizeof(root), home))
        return result_err("path too long");
    return install_vim_family("nvim", root);
}

static vigil_editor_result_t uninstall_nvim(const char *home)
{
    char root[1024];
    if (!nvim_root(root, sizeof(root), home))
        return result_ok("Done.");
    return uninstall_vim_family(root);
}

static int is_installed_nvim(const char *home)
{
    char root[1024];
    if (!nvim_root(root, sizeof(root), home))
        return 0;
    return is_installed_vim_family(root);
}

/* ── vscode ──────────────────────────────────────────────────────── */

static void vscode_pkg_content(char *buf, size_t cap)
{
    snprintf(buf, cap,
             "{\n"
             "  \"name\": \"vigil-lang\",\n"
             "  \"displayName\": \"Vigil\",\n"
             "  \"description\": \"Vigil language support\",\n"
             "  \"version\": \"0.1.0\",\n"
             "  \"publisher\": \"local\",\n"
             "  \"engines\": { \"vscode\": \"^1.75.0\" },\n"
             "  \"activationEvents\": [\"onLanguage:vigil\"],\n"
             "  \"contributes\": {\n"
             "    \"languages\": [{\n"
             "      \"id\": \"vigil\",\n"
             "      \"extensions\": [\".vigil\"],\n"
             "      \"configuration\": \"./language-configuration.json\"\n"
             "    }]\n"
             "  },\n"
             "  \"main\": \"./extension.js\",\n"
             "  \"dependencies\": {\n"
             "    \"vscode-languageclient\": \"^9.0.1\"\n"
             "  }\n"
             "}\n");
}

static void vscode_ext_content(char *buf, size_t cap, const char *vigil_bin)
{
    snprintf(buf, cap,
             "const vscode = require('vscode');\n"
             "const { LanguageClient } = require('vscode-languageclient/node');\n"
             "let client;\n"
             "function activate(context) {\n"
             "  const output = vscode.window.createOutputChannel('Vigil');\n"
             "  output.appendLine('Vigil extension activated');\n"
             "  client = new LanguageClient('vigil', 'Vigil LSP',\n"
             "    { command: '%s', args: ['lsp'] },\n"
             "    { documentSelector: [{ scheme: 'file', language: 'vigil' }],\n"
             "      outputChannel: output });\n"
             "  context.subscriptions.push(client.start());\n"
             "}\n"
             "function deactivate() { return client && client.stop(); }\n"
             "module.exports = { activate, deactivate };\n",
             vigil_bin);
}

static const char vscode_langconf[] = "{\n"
                                      "  \"comments\": { \"lineComment\": \"//\" },\n"
                                      "  \"brackets\": [[\"{\", \"}\"], [\"[\", \"]\"], [\"(\", \")\"]],\n"
                                      "  \"autoClosingPairs\": [\n"
                                      "    { \"open\": \"{\", \"close\": \"}\" },\n"
                                      "    { \"open\": \"[\", \"close\": \"]\" },\n"
                                      "    { \"open\": \"(\", \"close\": \")\" },\n"
                                      "    { \"open\": \"\\\"\", \"close\": \"\\\"\" }\n"
                                      "  ]\n"
                                      "}\n";

static int vscode_ext_dir(char *buf, size_t cap, const char *home)
{
    return pjoin(buf, cap, home, ".vscode") && pjoin(buf, cap, buf, "extensions") && pjoin(buf, cap, buf, "vigil-lang");
}

static vigil_editor_result_t install_vscode(const char *vigil_bin, const char *home)
{
    char ext_dir[1024], path[1024], content[2048];

    if (!vscode_ext_dir(ext_dir, sizeof(ext_dir), home))
        return result_err("path too long");
    vigil_platform_mkdir_p(ext_dir, NULL);

    if (!pjoin(path, sizeof(path), ext_dir, "package.json"))
        return result_err("path too long");
    vscode_pkg_content(content, sizeof(content));
    printf("Creating %s\n", path);
    if (!pwrite(path, content))
        return result_err("failed to write package.json");

    if (!pjoin(path, sizeof(path), ext_dir, "extension.js"))
        return result_err("path too long");
    vscode_ext_content(content, sizeof(content), vigil_bin);
    printf("Creating %s\n", path);
    if (!pwrite(path, content))
        return result_err("failed to write extension.js");

    if (!pjoin(path, sizeof(path), ext_dir, "language-configuration.json"))
        return result_err("path too long");
    printf("Creating %s\n", path);
    if (!pwrite(path, vscode_langconf))
    {
        return result_err("failed to write language config");
    }

    /* Install npm dependencies (not available on iOS/Android/Emscripten) */
#if !defined(__EMSCRIPTEN__) && !defined(__ANDROID__) && !(defined(__APPLE__) && TARGET_OS_IPHONE)
    printf("Running npm install in %s\n", ext_dir);
    {
        char cmd[1200];
#ifdef _WIN32
        snprintf(cmd, sizeof(cmd), "cd /d \"%s\" && npm install --silent 2>nul", ext_dir);
#else
        snprintf(cmd, sizeof(cmd), "cd \"%s\" && npm install --silent 2>&1", ext_dir);
#endif
        int rc = system(cmd);
        if (rc != 0)
            return result_err("npm install failed - is Node.js installed?");
    }
#endif

    return result_ok("Done. Reload VS Code and open a .vigil file.\n"
                     "To undo: vigil editor uninstall vscode");
}

static vigil_editor_result_t uninstall_vscode(const char *home)
{
    char ext_dir[1024], path[1024];
    if (!vscode_ext_dir(ext_dir, sizeof(ext_dir), home))
        return result_ok("Done.");

    const char *files[] = {"package.json", "extension.js", "language-configuration.json", "package-lock.json", NULL};
    for (const char *const *f = files; *f; f++)
    {
        if (pjoin(path, sizeof(path), ext_dir, *f))
            premove(path);
    }
    /* Remove node_modules */
    if (pjoin(path, sizeof(path), ext_dir, "node_modules"))
    {
        printf("Removing %s\n", path);
        vigil_platform_remove_all(path, NULL);
    }
    return result_ok("Done.");
}

static int is_installed_vscode(const char *home)
{
    char path[1024], ext_dir[1024];
    if (!vscode_ext_dir(ext_dir, sizeof(ext_dir), home))
        return 0;
    if (!pjoin(path, sizeof(path), ext_dir, "package.json"))
        return 0;
    return pexists(path);
}

/* ── emacs ───────────────────────────────────────────────────────── */

static const char emacs_marker_begin[] = ";; BEGIN vigil editor integration\n";
static const char emacs_marker_end[] = ";; END vigil editor integration\n";

static int emacs_escape_string(const char *input, char *out, size_t cap)
{
    size_t i;
    size_t j = 0;
    for (i = 0; input[i] != '\0'; i++)
    {
        if (j + 2 >= cap)
            return 0;
        if (input[i] == '\\' || input[i] == '"')
            out[j++] = '\\';
        out[j++] = input[i];
    }
    if (j >= cap)
        return 0;
    out[j] = '\0';
    return 1;
}

static int emacs_init_path(char *buf, size_t cap, const char *home)
{
    char dir[1024];
    if (!emacs_dir(dir, sizeof(dir), home))
        return 0;
    return pjoin(buf, cap, dir, "init.el");
}

static int emacs_mode_path(char *buf, size_t cap, const char *home)
{
    char dir[1024];
    if (!emacs_dir(dir, sizeof(dir), home))
        return 0;
    return pjoin(buf, cap, dir, "vigil-mode.el");
}

static int emacs_init_block(char *buf, size_t cap, const char *mode_path)
{
    char escaped[2048];
    if (!emacs_escape_string(mode_path, escaped, sizeof(escaped)))
        return 0;
    snprintf(buf, cap,
             "%s"
             "(load-file \"%s\")\n"
             "(add-to-list 'auto-mode-alist '(\"\\\\.vigil\\\\'\" . vigil-mode))\n"
             "%s",
             emacs_marker_begin, escaped, emacs_marker_end);
    return 1;
}

static int emacs_write_init_with_block(const char *init_path, const char *existing, size_t existing_length,
                                       const char *block)
{
    size_t block_length = strlen(block);
    size_t needs_newline = 0;
    size_t out_length;
    char *out;

    if (existing && strstr(existing, emacs_marker_begin) != NULL)
        return 1;
    if (existing_length > 0 && existing[existing_length - 1] != '\n')
        needs_newline = 1;
    out_length = existing_length + needs_newline + block_length;
    out = (char *)malloc(out_length + 1);
    if (!out)
        return 0;
    if (existing_length > 0)
        memcpy(out, existing, existing_length);
    if (needs_newline)
        out[existing_length] = '\n';
    memcpy(out + existing_length + needs_newline, block, block_length);
    out[out_length] = '\0';

    if (!pwrite_len(init_path, out, out_length))
    {
        free(out);
        return 0;
    }
    free(out);
    return 1;
}

static vigil_editor_result_t install_emacs(const char *vigil_bin, const char *home)
{
    char dir[1024], init_path[1024], mode_path[1024], block[3072];
    char *init_content = NULL;
    size_t init_length = 0;
    (void)vigil_bin;

    if (!emacs_dir(dir, sizeof(dir), home) || !emacs_init_path(init_path, sizeof(init_path), home) ||
        !emacs_mode_path(mode_path, sizeof(mode_path), home))
        return result_err("path too long");
    if (!ensure_dir(dir))
        return result_err("failed to create emacs config directory");

    printf("Creating %s\n", mode_path);
    if (!pwrite(mode_path, emacs_mode_content))
        return result_err("failed to write emacs mode");
    if (!emacs_init_block(block, sizeof(block), mode_path))
        return result_err("failed to build emacs init block");

    if (pread(init_path, &init_content, &init_length))
    {
        if (!emacs_write_init_with_block(init_path, init_content, init_length, block))
        {
            free(init_content);
            return result_err("failed to update init.el");
        }
        free(init_content);
    }
    else
    {
        printf("Creating %s\n", init_path);
        if (!pwrite(init_path, block))
            return result_err("failed to write init.el");
    }

    return result_ok("Done. Restart Emacs or reload init.el.\nTo undo: vigil editor uninstall emacs");
}

static vigil_editor_result_t uninstall_emacs(const char *home)
{
    char init_path[1024], mode_path[1024];
    char *init_content = NULL;
    size_t init_length = 0;
    char *begin;
    char *end;

    if (!emacs_init_path(init_path, sizeof(init_path), home) || !emacs_mode_path(mode_path, sizeof(mode_path), home))
        return result_ok("Done.");

    premove(mode_path);

    if (!pread(init_path, &init_content, &init_length))
        return result_ok("Done.");

    begin = strstr(init_content, emacs_marker_begin);
    end = strstr(init_content, emacs_marker_end);
    if (begin && end && end >= begin)
    {
        size_t prefix_len = (size_t)(begin - init_content);
        size_t suffix_offset = (size_t)(end - init_content) + strlen(emacs_marker_end);
        size_t suffix_len = init_length - suffix_offset;
        memmove(begin, init_content + suffix_offset, suffix_len);
        init_length = prefix_len + suffix_len;
        if (!pwrite_len(init_path, init_content, init_length))
        {
            free(init_content);
            return result_err("failed to update init.el");
        }
    }
    free(init_content);
    return result_ok("Done.");
}

static int is_installed_emacs(const char *home)
{
    char mode_path[1024];
    if (!emacs_mode_path(mode_path, sizeof(mode_path), home))
        return 0;
    return pexists(mode_path);
}

/* ── sublime ─────────────────────────────────────────────────────── */

static int sublime_package_dir(char *buf, size_t cap, const char *home)
{
    if (!sublime_root(buf, cap, home))
        return 0;
    return pjoin(buf, cap, buf, "Vigil");
}

static int sublime_syntax_path(char *buf, size_t cap, const char *home)
{
    char dir[1024];
    if (!sublime_package_dir(dir, sizeof(dir), home))
        return 0;
    return pjoin(buf, cap, dir, "Vigil.sublime-syntax");
}

static vigil_editor_result_t install_sublime(const char *vigil_bin, const char *home)
{
    char dir[1024], syntax_path[1024];
    (void)vigil_bin;
    if (!sublime_package_dir(dir, sizeof(dir), home) || !sublime_syntax_path(syntax_path, sizeof(syntax_path), home))
        return result_err("path too long");
    if (!ensure_dir(dir))
        return result_err("failed to create sublime package directory");
    printf("Creating %s\n", syntax_path);
    if (!pwrite(syntax_path, sublime_syntax_content))
        return result_err("failed to write sublime syntax");
    return result_ok("Done. Restart Sublime Text or reopen the file.\nTo undo: vigil editor uninstall sublime");
}

static vigil_editor_result_t uninstall_sublime(const char *home)
{
    char dir[1024];
    if (!sublime_package_dir(dir, sizeof(dir), home))
        return result_ok("Done.");
    if (pexists(dir))
    {
        printf("Removing %s\n", dir);
        vigil_platform_remove_all(dir, NULL);
    }
    return result_ok("Done.");
}

static int is_installed_sublime(const char *home)
{
    char syntax_path[1024];
    if (!sublime_syntax_path(syntax_path, sizeof(syntax_path), home))
        return 0;
    return pexists(syntax_path);
}

/* ── supported editors ───────────────────────────────────────────── */

typedef vigil_editor_result_t (*editor_install_fn)(const char *vigil_bin, const char *home);
typedef vigil_editor_result_t (*editor_uninstall_fn)(const char *home);
typedef int (*editor_installed_fn)(const char *home);

typedef struct editor_ops
{
    const char *name;
    editor_install_fn install;
    editor_uninstall_fn uninstall;
    editor_installed_fn is_installed;
} editor_ops_t;

static const editor_ops_t editor_ops[] = {
    {"vim", install_vim, uninstall_vim, is_installed_vim},
    {"nvim", install_nvim, uninstall_nvim, is_installed_nvim},
    {"vscode", install_vscode, uninstall_vscode, is_installed_vscode},
    {"emacs", install_emacs, uninstall_emacs, is_installed_emacs},
    {"sublime", install_sublime, uninstall_sublime, is_installed_sublime},
    {NULL, NULL, NULL, NULL},
};

static const char *const supported_editors[] = {"vim", "nvim", "vscode", "emacs", "sublime", NULL};

static const editor_ops_t *find_editor(const char *name)
{
    const editor_ops_t *editor;
    if (!name)
        return NULL;
    for (editor = editor_ops; editor->name; editor++)
    {
        if (strcmp(editor->name, name) == 0)
            return editor;
    }
    return NULL;
}

VIGIL_API const char *const *vigil_editor_supported(void)
{
    return supported_editors;
}

VIGIL_API int vigil_editor_is_supported(const char *name)
{
    return find_editor(name) != NULL;
}

/* ── public dispatch ─────────────────────────────────────────────── */

VIGIL_API vigil_editor_result_t vigil_editor_install(const char *name, const char *vigil_bin, const char *home)
{
    const editor_ops_t *editor;
    if (!name || !vigil_bin || !home)
        return result_err("invalid arguments");
    editor = find_editor(name);
    if (editor)
        return editor->install(vigil_bin, home);
    return result_err("unknown editor");
}

VIGIL_API vigil_editor_result_t vigil_editor_uninstall(const char *name, const char *home)
{
    const editor_ops_t *editor;
    if (!name || !home)
        return result_err("invalid arguments");
    editor = find_editor(name);
    if (editor)
        return editor->uninstall(home);
    return result_err("unknown editor");
}

VIGIL_API int vigil_editor_is_installed(const char *name, const char *home)
{
    const editor_ops_t *editor;
    if (!name || !home)
        return 0;
    editor = find_editor(name);
    if (editor)
        return editor->is_installed(home);
    return 0;
}
