/* Generated by vigil transpile — do not edit. */
#include "vigil_generated.h"
#include <math.h>
#include <string.h>
#include "vigil/transpile_rt.h"
#include "vigil/value.h"

vigil_value_t *vigil_fn_constants[3];
size_t vigil_fn_constant_counts[3];

static vigil_reg_t vigil_fn_0(vigil_tc_t *tc, vigil_reg_t arg_0, vigil_reg_t arg_1);
static vigil_reg_t vigil_fn_1(vigil_tc_t *tc, vigil_reg_t arg_0);
vigil_reg_t vigil_fn_2(vigil_tc_t *tc);

vigil_reg_t vigil_fn_0(vigil_tc_t *tc, vigil_reg_t arg_0, vigil_reg_t arg_1)
{
    vigil_reg_t r[8];
    memset(r, 0, sizeof(r));
    r[0] = arg_0;
    r[1] = arg_1;
    tc->constants = vigil_fn_constants[0];
    tc->constant_count = vigil_fn_constant_counts[0];

L_0:;
    vigil_tc_move_reg(&r[2].v, r[1].v);
L_1:;
    r[3].i = (int64_t)0LL;
L_2:;
    if ((int32_t)r[2].i == (int32_t)r[3].i) goto L_4;
L_3:;
    goto L_11;
L_4:;
    r[4].i = (int64_t)0LL;
L_5:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "division by zero", 16, &_s, NULL); vigil_value_init_object(&r[5].v, &_s); }
L_6:;
    r[6].i = (int64_t)9LL;
L_7:;
    vigil_tc_new_error(tc, &r[5].v, &r[5].v, &r[6].v, NULL);
L_8:;
    vigil_tc_move_reg(&r[0].v, r[4].v);
L_9:;
    vigil_tc_move_reg(&r[1].v, r[5].v);
L_10:;
    tc->ret_count = 2;
    tc->ret_buf[1] = r[1].v;
    return r[0];
L_11:;
    vigil_tc_move_reg(&r[4].v, r[0].v);
L_12:;
L_13:;
    r[6].i = (int64_t)((int32_t)r[4].i / (int32_t)r[1].i);
L_14:;
    r[7].v = vigil_value_copy(&tc->constants[4]);
L_15:;
    vigil_tc_move_reg(&r[0].v, r[6].v);
L_16:;
    vigil_tc_move_reg(&r[1].v, r[7].v);
L_17:;
    tc->ret_count = 2;
    tc->ret_buf[1] = r[1].v;
    return r[0];
    return (vigil_reg_t){0};
}

vigil_reg_t vigil_fn_1(vigil_tc_t *tc, vigil_reg_t arg_0)
{
    vigil_reg_t r[7];
    memset(r, 0, sizeof(r));
    r[0] = arg_0;
    tc->constants = vigil_fn_constants[1];
    tc->constant_count = vigil_fn_constant_counts[1];

L_0:;
L_1:;
    if ((int32_t)r[0].i < (int32_t)0) goto L_3;
L_2:;
    goto L_8;
L_3:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "age cannot be negative", 22, &_s, NULL); vigil_value_init_object(&r[3].v, &_s); }
L_4:;
    r[4].i = (int64_t)9LL;
L_5:;
    vigil_tc_new_error(tc, &r[3].v, &r[3].v, &r[4].v, NULL);
L_6:;
L_7:;
    tc->ret_count = 1;
    return r[3];
L_8:;
    vigil_tc_move_reg(&r[3].v, r[0].v);
L_9:;
    r[4].i = (int64_t)150LL;
L_10:;
    if ((int32_t)r[3].i > (int32_t)r[4].i) goto L_12;
L_11:;
    goto L_17;
L_12:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "age is unrealistic", 18, &_s, NULL); vigil_value_init_object(&r[5].v, &_s); }
L_13:;
    r[6].i = (int64_t)9LL;
L_14:;
    vigil_tc_new_error(tc, &r[5].v, &r[5].v, &r[6].v, NULL);
L_15:;
L_16:;
    tc->ret_count = 1;
    return r[5];
L_17:;
    r[5].v = vigil_value_copy(&tc->constants[6]);
L_18:;
L_19:;
    tc->ret_count = 1;
    return r[5];
    return (vigil_reg_t){0};
}

vigil_reg_t vigil_fn_2(vigil_tc_t *tc)
{
    vigil_reg_t r[17];
    memset(r, 0, sizeof(r));
    tc->constants = vigil_fn_constants[2];
    tc->constant_count = vigil_fn_constant_counts[2];

L_0:;
    r[0].i = (int64_t)10LL;
L_1:;
    r[1].i = (int64_t)2LL;
L_2:;
    { const vigil_value_t *_sc = tc->constants; size_t _sn = tc->constant_count;
    r[0] = vigil_fn_0(tc, r[0], r[1]);
    { uint8_t _ri; for (_ri = 1; _ri < tc->ret_count; _ri++) r[0 + _ri].v = tc->ret_buf[_ri]; }
    tc->constants = _sc; tc->constant_count = _sn; }
L_3:;
    vigil_tc_move_reg(&r[2].v, r[1].v);
L_4:;
    r[3].v = vigil_value_copy(&tc->constants[2]);
L_5:;
    r[2].i = vigil_tc_values_equal((uint64_t *)r, 2, 3);
L_6:;
    r[2].i = !r[2].i;
L_7:;
    if (vigil_tc_is_truthy(r[2].v)) goto L_9;
L_8:;
    goto L_19;
L_9:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "Error: ", 7, &_s, NULL); vigil_value_init_object(&r[2].v, &_s); }
L_10:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 126, 3, 0, 0, NULL);
L_11:;
    vigil_tc_move_reg(&r[3].v, r[1].v);
L_12:;
    vigil_tc_get_error_msg(tc, &r[3].v, &r[3].v, NULL);
L_13:;
    vigil_tc_generic_add(tc, &r[2].v, &r[2].v, &r[3].v, NULL);
L_14:;
    vigil_tc_call_native(tc, (uint64_t *)r, 2, 1, 4, NULL);
L_16:;
    r[2].i = (int64_t)1LL;
L_17:;
L_18:;
    tc->ret_count = 1;
    return r[2];
L_19:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "10 / 2 = ", 9, &_s, NULL); vigil_value_init_object(&r[2].v, &_s); }
L_20:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 126, 3, 0, 0, NULL);
L_21:;
    vigil_tc_move_reg(&r[3].v, r[0].v);
L_22:;
    vigil_tc_to_string(tc, &r[3].v, &r[3].v, NULL);
L_23:;
    vigil_tc_generic_add(tc, &r[2].v, &r[2].v, &r[3].v, NULL);
L_24:;
    vigil_tc_call_native(tc, (uint64_t *)r, 2, 1, 7, NULL);
L_26:;
    r[2].i = (int64_t)10LL;
L_27:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 126, 3, 0, 0, NULL);
L_28:;
    r[3].i = (int64_t)0LL;
L_29:;
    { const vigil_value_t *_sc = tc->constants; size_t _sn = tc->constant_count;
    r[2] = vigil_fn_0(tc, r[2], r[3]);
    { uint8_t _ri; for (_ri = 1; _ri < tc->ret_count; _ri++) r[2 + _ri].v = tc->ret_buf[_ri]; }
    tc->constants = _sc; tc->constant_count = _sn; }
L_30:;
    vigil_tc_move_reg(&r[4].v, r[3].v);
L_31:;
    r[5].v = vigil_value_copy(&tc->constants[10]);
L_32:;
    r[4].i = vigil_tc_values_equal((uint64_t *)r, 4, 5);
L_33:;
    r[4].i = !r[4].i;
L_34:;
    if (vigil_tc_is_truthy(r[4].v)) goto L_36;
L_35:;
    goto L_44;
L_36:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "Error: ", 7, &_s, NULL); vigil_value_init_object(&r[4].v, &_s); }
L_37:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 126, 5, 0, 0, NULL);
L_38:;
    vigil_tc_move_reg(&r[5].v, r[3].v);
L_39:;
    vigil_tc_get_error_msg(tc, &r[5].v, &r[5].v, NULL);
L_40:;
    vigil_tc_generic_add(tc, &r[4].v, &r[4].v, &r[5].v, NULL);
L_41:;
    vigil_tc_call_native(tc, (uint64_t *)r, 4, 1, 12, NULL);
L_43:;
    goto L_51;
L_44:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "Result: ", 8, &_s, NULL); vigil_value_init_object(&r[4].v, &_s); }
L_45:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 126, 5, 0, 0, NULL);
L_46:;
    vigil_tc_move_reg(&r[5].v, r[2].v);
L_47:;
    vigil_tc_to_string(tc, &r[5].v, &r[5].v, NULL);
L_48:;
    vigil_tc_generic_add(tc, &r[4].v, &r[4].v, &r[5].v, NULL);
L_49:;
    vigil_tc_call_native(tc, (uint64_t *)r, 4, 1, 14, NULL);
L_51:;
    r[4].i = (int64_t)25LL;
L_52:;
    { const vigil_value_t *_sc = tc->constants; size_t _sn = tc->constant_count;
    r[4] = vigil_fn_1(tc, r[4]);
    { uint8_t _ri; for (_ri = 1; _ri < tc->ret_count; _ri++) r[4 + _ri].v = tc->ret_buf[_ri]; }
    tc->constants = _sc; tc->constant_count = _sn; }
L_53:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 126, 5, 0, 0, NULL);
L_54:;
    vigil_tc_move_reg(&r[5].v, r[4].v);
L_55:;
    r[6].v = vigil_value_copy(&tc->constants[16]);
L_56:;
    r[5].i = vigil_tc_values_equal((uint64_t *)r, 5, 6);
L_57:;
    if (vigil_tc_is_truthy(r[5].v)) goto L_59;
L_58:;
    goto L_63;
L_59:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "Age 25 is valid", 15, &_s, NULL); vigil_value_init_object(&r[5].v, &_s); }
L_60:;
    vigil_tc_call_native(tc, (uint64_t *)r, 5, 1, 18, NULL);
L_62:;
    goto L_63;
L_63:;
    r[5].i = (int64_t)5LL;
L_64:;
    r[5].i = -r[5].i;
L_65:;
    r[5].i = (int64_t)(int32_t)r[5].i;
L_66:;
    { const vigil_value_t *_sc = tc->constants; size_t _sn = tc->constant_count;
    r[5] = vigil_fn_1(tc, r[5]);
    { uint8_t _ri; for (_ri = 1; _ri < tc->ret_count; _ri++) r[5 + _ri].v = tc->ret_buf[_ri]; }
    tc->constants = _sc; tc->constant_count = _sn; }
L_67:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 126, 6, 0, 0, NULL);
L_68:;
    vigil_tc_move_reg(&r[6].v, r[5].v);
L_69:;
    r[7].v = vigil_value_copy(&tc->constants[20]);
L_70:;
    r[6].i = vigil_tc_values_equal((uint64_t *)r, 6, 7);
L_71:;
    r[6].i = !r[6].i;
L_72:;
    if (vigil_tc_is_truthy(r[6].v)) goto L_74;
L_73:;
    goto L_82;
L_74:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "Invalid age: ", 13, &_s, NULL); vigil_value_init_object(&r[6].v, &_s); }
L_75:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 126, 7, 0, 0, NULL);
L_76:;
    vigil_tc_move_reg(&r[7].v, r[5].v);
L_77:;
    vigil_tc_get_error_msg(tc, &r[7].v, &r[7].v, NULL);
L_78:;
    vigil_tc_generic_add(tc, &r[6].v, &r[6].v, &r[7].v, NULL);
L_79:;
    vigil_tc_call_native(tc, (uint64_t *)r, 6, 1, 22, NULL);
L_81:;
    goto L_82;
L_82:;
    r[6].i = (int64_t)200LL;
L_83:;
    { const vigil_value_t *_sc = tc->constants; size_t _sn = tc->constant_count;
    r[6] = vigil_fn_1(tc, r[6]);
    { uint8_t _ri; for (_ri = 1; _ri < tc->ret_count; _ri++) r[6 + _ri].v = tc->ret_buf[_ri]; }
    tc->constants = _sc; tc->constant_count = _sn; }
L_84:;
    vigil_tc_vm_op(tc, (uint64_t *)r, 126, 7, 0, 0, NULL);
L_85:;
    vigil_tc_move_reg(&r[7].v, r[6].v);
L_86:;
    r[8].v = vigil_value_copy(&tc->constants[24]);
L_87:;
    r[7].i = vigil_tc_values_equal((uint64_t *)r, 7, 8);
L_88:;
    r[7].i = !r[7].i;
L_89:;
    if (vigil_tc_is_truthy(r[7].v)) goto L_91;
L_90:;
    goto L_98;
L_91:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "Invalid age: ", 13, &_s, NULL); vigil_value_init_object(&r[7].v, &_s); }
L_92:;
    vigil_tc_move_reg(&r[9].v, r[6].v);
L_93:;
    vigil_tc_get_error_msg(tc, &r[9].v, &r[9].v, NULL);
L_94:;
    vigil_tc_generic_add(tc, &r[7].v, &r[7].v, &r[9].v, NULL);
L_95:;
    vigil_tc_call_native(tc, (uint64_t *)r, 7, 1, 26, NULL);
L_97:;
    goto L_98;
L_98:;
    r[7].i = (int64_t)20LL;
L_99:;
    r[10].i = (int64_t)4LL;
L_100:;
    vigil_tc_move_reg(&r[11].v, r[7].v);
L_101:;
    vigil_tc_move_reg(&r[12].v, r[10].v);
L_102:;
    { const vigil_value_t *_sc = tc->constants; size_t _sn = tc->constant_count;
    r[11] = vigil_fn_0(tc, r[11], r[12]);
    { uint8_t _ri; for (_ri = 1; _ri < tc->ret_count; _ri++) r[11 + _ri].v = tc->ret_buf[_ri]; }
    tc->constants = _sc; tc->constant_count = _sn; }
L_103:;
    vigil_tc_move_reg(&r[7].v, r[11].v);
L_104:;
    { vigil_object_t *_s = NULL; vigil_string_object_new(tc->runtime, "20 / 4 = ", 9, &_s, NULL); vigil_value_init_object(&r[13].v, &_s); }
L_105:;
    vigil_tc_move_reg(&r[14].v, r[7].v);
L_106:;
    vigil_tc_to_string(tc, &r[14].v, &r[14].v, NULL);
L_107:;
    vigil_tc_generic_add(tc, &r[15].v, &r[13].v, &r[14].v, NULL);
L_108:;
    vigil_tc_call_native(tc, (uint64_t *)r, 15, 1, 30, NULL);
L_110:;
    r[16].i = (int64_t)0LL;
L_111:;
L_112:;
    tc->ret_count = 1;
    return r[16];
    return (vigil_reg_t){0};
}

